package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnP1mCatalogoRuta generated by hbm2java
 */
@Entity
@Table(name="en_p1m_catalogo_ruta"
    ,catalog="episerp"
)
public class EnP1mCatalogoRuta  implements java.io.Serializable {


     private Integer catRutCod;
     private String catRutDet;
     private char estRegCod;
     private Set enP1mClientesRutases = new HashSet(0);

    public EnP1mCatalogoRuta() {
    }

	
    public EnP1mCatalogoRuta(String catRutDet, char estRegCod) {
        this.catRutDet = catRutDet;
        this.estRegCod = estRegCod;
    }
    public EnP1mCatalogoRuta(String catRutDet, char estRegCod, Set enP1mClientesRutases) {
       this.catRutDet = catRutDet;
       this.estRegCod = estRegCod;
       this.enP1mClientesRutases = enP1mClientesRutases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CatRutCod", unique=true, nullable=false)
    public Integer getCatRutCod() {
        return this.catRutCod;
    }
    
    public void setCatRutCod(Integer catRutCod) {
        this.catRutCod = catRutCod;
    }

    
    @Column(name="CatRutDet", nullable=false, length=90)
    public String getCatRutDet() {
        return this.catRutDet;
    }
    
    public void setCatRutDet(String catRutDet) {
        this.catRutDet = catRutDet;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enP1mCatalogoRuta")
    public Set getEnP1mClientesRutases() {
        return this.enP1mClientesRutases;
    }
    
    public void setEnP1mClientesRutases(Set enP1mClientesRutases) {
        this.enP1mClientesRutases = enP1mClientesRutases;
    }




}


