package org.epis.minierp.model;
// Generated 31/10/2016 01:37:15 AM by Hibernate Tools 4.3.1



/**
 * EnP1tFacturaVentaDet generated by hbm2java
 */
public class EnP1tFacturaVentaDet  implements java.io.Serializable {


     private EnP1tFacturaVentaDetId id;
     private EnP1mFacturaVentaCab enP1mFacturaVentaCab;
     private EnP2mProducto enP2mProducto;
     private double facVenDetCan;
     private double facVenDetValUni;

    public EnP1tFacturaVentaDet() {
    }

    public EnP1tFacturaVentaDet(EnP1tFacturaVentaDetId id, EnP1mFacturaVentaCab enP1mFacturaVentaCab, EnP2mProducto enP2mProducto, double facVenDetCan, double facVenDetValUni) {
       this.id = id;
       this.enP1mFacturaVentaCab = enP1mFacturaVentaCab;
       this.enP2mProducto = enP2mProducto;
       this.facVenDetCan = facVenDetCan;
       this.facVenDetValUni = facVenDetValUni;
    }
   
    public EnP1tFacturaVentaDetId getId() {
        return this.id;
    }
    
    public void setId(EnP1tFacturaVentaDetId id) {
        this.id = id;
    }
    public EnP1mFacturaVentaCab getEnP1mFacturaVentaCab() {
        return this.enP1mFacturaVentaCab;
    }
    
    public void setEnP1mFacturaVentaCab(EnP1mFacturaVentaCab enP1mFacturaVentaCab) {
        this.enP1mFacturaVentaCab = enP1mFacturaVentaCab;
    }
    public EnP2mProducto getEnP2mProducto() {
        return this.enP2mProducto;
    }
    
    public void setEnP2mProducto(EnP2mProducto enP2mProducto) {
        this.enP2mProducto = enP2mProducto;
    }
    public double getFacVenDetCan() {
        return this.facVenDetCan;
    }
    
    public void setFacVenDetCan(double facVenDetCan) {
        this.facVenDetCan = facVenDetCan;
    }
    public double getFacVenDetValUni() {
        return this.facVenDetValUni;
    }
    
    public void setFacVenDetValUni(double facVenDetValUni) {
        this.facVenDetValUni = facVenDetValUni;
    }




}


