package org.epis.minierp.model;
// Generated 13/10/2016 06:03:52 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnP1mMovimientoPuntoVen generated by hbm2java
 */
@Entity
@Table(name="en_p1m_movimiento_punto_ven"
    ,catalog="episerp"
)
public class EnP1mMovimientoPuntoVen  implements java.io.Serializable {


     private EnP1mMovimientoPuntoVenId id;
     private EnP1mPuntoVenta enP1mPuntoVenta;
     private int movPunVenCom;
     private String movPunVenComCod;
     private char estRegCod;

    public EnP1mMovimientoPuntoVen() {
    }

    public EnP1mMovimientoPuntoVen(EnP1mMovimientoPuntoVenId id, EnP1mPuntoVenta enP1mPuntoVenta, int movPunVenCom, String movPunVenComCod, char estRegCod) {
       this.id = id;
       this.enP1mPuntoVenta = enP1mPuntoVenta;
       this.movPunVenCom = movPunVenCom;
       this.movPunVenComCod = movPunVenComCod;
       this.estRegCod = estRegCod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="movPunVenCod", column=@Column(name="MovPunVenCod", nullable=false) ), 
        @AttributeOverride(name="sucCod", column=@Column(name="SucCod", nullable=false) ), 
        @AttributeOverride(name="punVenCod", column=@Column(name="PunVenCod", nullable=false) ) } )
    public EnP1mMovimientoPuntoVenId getId() {
        return this.id;
    }
    
    public void setId(EnP1mMovimientoPuntoVenId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="SucCod", referencedColumnName="PunVenCod", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PunVenCod", referencedColumnName="SucCod", nullable=false, insertable=false, updatable=false) } )
    public EnP1mPuntoVenta getEnP1mPuntoVenta() {
        return this.enP1mPuntoVenta;
    }
    
    public void setEnP1mPuntoVenta(EnP1mPuntoVenta enP1mPuntoVenta) {
        this.enP1mPuntoVenta = enP1mPuntoVenta;
    }

    
    @Column(name="MovPunVenCom", nullable=false)
    public int getMovPunVenCom() {
        return this.movPunVenCom;
    }
    
    public void setMovPunVenCom(int movPunVenCom) {
        this.movPunVenCom = movPunVenCom;
    }

    
    @Column(name="MovPunVenComCod", nullable=false, length=10)
    public String getMovPunVenComCod() {
        return this.movPunVenComCod;
    }
    
    public void setMovPunVenComCod(String movPunVenComCod) {
        this.movPunVenComCod = movPunVenComCod;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


