package org.epis.minierp.model;
// Generated 28/10/2016 01:30:37 PM by Hibernate Tools 4.3.1



/**
 * EnP1mEmpresa generated by hbm2java
 */
public class EnP1mEmpresa  implements java.io.Serializable {


     private Integer empCod;
     private String empNom;
     private String empDes;
     private String empDir;
     private String empTel;
     private String empCor;
     private double empIgv;
     private String empRuc;
     private byte[] empImg;

    public EnP1mEmpresa() {
    }

	
    public EnP1mEmpresa(String empNom, String empDir, double empIgv, String empRuc) {
        this.empNom = empNom;
        this.empDir = empDir;
        this.empIgv = empIgv;
        this.empRuc = empRuc;
    }
    public EnP1mEmpresa(String empNom, String empDes, String empDir, String empTel, String empCor, double empIgv, String empRuc, byte[] empImg) {
       this.empNom = empNom;
       this.empDes = empDes;
       this.empDir = empDir;
       this.empTel = empTel;
       this.empCor = empCor;
       this.empIgv = empIgv;
       this.empRuc = empRuc;
       this.empImg = empImg;
    }
   
    public Integer getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(Integer empCod) {
        this.empCod = empCod;
    }
    public String getEmpNom() {
        return this.empNom;
    }
    
    public void setEmpNom(String empNom) {
        this.empNom = empNom;
    }
    public String getEmpDes() {
        return this.empDes;
    }
    
    public void setEmpDes(String empDes) {
        this.empDes = empDes;
    }
    public String getEmpDir() {
        return this.empDir;
    }
    
    public void setEmpDir(String empDir) {
        this.empDir = empDir;
    }
    public String getEmpTel() {
        return this.empTel;
    }
    
    public void setEmpTel(String empTel) {
        this.empTel = empTel;
    }
    public String getEmpCor() {
        return this.empCor;
    }
    
    public void setEmpCor(String empCor) {
        this.empCor = empCor;
    }
    public double getEmpIgv() {
        return this.empIgv;
    }
    
    public void setEmpIgv(double empIgv) {
        this.empIgv = empIgv;
    }
    public String getEmpRuc() {
        return this.empRuc;
    }
    
    public void setEmpRuc(String empRuc) {
        this.empRuc = empRuc;
    }
    public byte[] getEmpImg() {
        return this.empImg;
    }
    
    public void setEmpImg(byte[] empImg) {
        this.empImg = empImg;
    }




}


