package org.epis.minierp.model;
// Generated 29/10/2016 12:36:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnP1mTipoComision generated by hbm2java
 */
public class EnP1mTipoComision  implements java.io.Serializable {


     private Integer tipComCod;
     private String tipComDet;
     private Integer tipComVal;
     private Character estRegCod;
     private Set enP1mFacturaVentaCabs = new HashSet(0);

    public EnP1mTipoComision() {
    }

    public EnP1mTipoComision(String tipComDet, Integer tipComVal, Character estRegCod, Set enP1mFacturaVentaCabs) {
       this.tipComDet = tipComDet;
       this.tipComVal = tipComVal;
       this.estRegCod = estRegCod;
       this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
    }
   
    public Integer getTipComCod() {
        return this.tipComCod;
    }
    
    public void setTipComCod(Integer tipComCod) {
        this.tipComCod = tipComCod;
    }
    public String getTipComDet() {
        return this.tipComDet;
    }
    
    public void setTipComDet(String tipComDet) {
        this.tipComDet = tipComDet;
    }
    public Integer getTipComVal() {
        return this.tipComVal;
    }
    
    public void setTipComVal(Integer tipComVal) {
        this.tipComVal = tipComVal;
    }
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP1mFacturaVentaCabs() {
        return this.enP1mFacturaVentaCabs;
    }
    
    public void setEnP1mFacturaVentaCabs(Set enP1mFacturaVentaCabs) {
        this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
    }




}


