package org.epis.minierp.model;
// Generated 09/11/2016 04:17:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EnP1cDevolucionVentas generated by hbm2java
 */
public class EnP1cDevolucionVentas  implements java.io.Serializable {


     private String facVenCabCod;
     private EnP1mFacturaVentaCab enP1mFacturaVentaCabByDevVenNewFac;
     private EnP1mFacturaVentaCab enP1mFacturaVentaCabByFacVenCabCod;
     private TaGzzTipoDevolucion taGzzTipoDevolucion;
     private String devVenDet;
     private Date devVenFec;
     private double devVenMon;

    public EnP1cDevolucionVentas() {
    }

	
    public EnP1cDevolucionVentas(EnP1mFacturaVentaCab enP1mFacturaVentaCabByFacVenCabCod, Date devVenFec, double devVenMon) {
        this.enP1mFacturaVentaCabByFacVenCabCod = enP1mFacturaVentaCabByFacVenCabCod;
        this.devVenFec = devVenFec;
        this.devVenMon = devVenMon;
    }
    public EnP1cDevolucionVentas(EnP1mFacturaVentaCab enP1mFacturaVentaCabByDevVenNewFac, EnP1mFacturaVentaCab enP1mFacturaVentaCabByFacVenCabCod, TaGzzTipoDevolucion taGzzTipoDevolucion, String devVenDet, Date devVenFec, double devVenMon) {
       this.enP1mFacturaVentaCabByDevVenNewFac = enP1mFacturaVentaCabByDevVenNewFac;
       this.enP1mFacturaVentaCabByFacVenCabCod = enP1mFacturaVentaCabByFacVenCabCod;
       this.taGzzTipoDevolucion = taGzzTipoDevolucion;
       this.devVenDet = devVenDet;
       this.devVenFec = devVenFec;
       this.devVenMon = devVenMon;
    }
   
    public String getFacVenCabCod() {
        return this.facVenCabCod;
    }
    
    public void setFacVenCabCod(String facVenCabCod) {
        this.facVenCabCod = facVenCabCod;
    }
    public EnP1mFacturaVentaCab getEnP1mFacturaVentaCabByDevVenNewFac() {
        return this.enP1mFacturaVentaCabByDevVenNewFac;
    }
    
    public void setEnP1mFacturaVentaCabByDevVenNewFac(EnP1mFacturaVentaCab enP1mFacturaVentaCabByDevVenNewFac) {
        this.enP1mFacturaVentaCabByDevVenNewFac = enP1mFacturaVentaCabByDevVenNewFac;
    }
    public EnP1mFacturaVentaCab getEnP1mFacturaVentaCabByFacVenCabCod() {
        return this.enP1mFacturaVentaCabByFacVenCabCod;
    }
    
    public void setEnP1mFacturaVentaCabByFacVenCabCod(EnP1mFacturaVentaCab enP1mFacturaVentaCabByFacVenCabCod) {
        this.enP1mFacturaVentaCabByFacVenCabCod = enP1mFacturaVentaCabByFacVenCabCod;
    }
    public TaGzzTipoDevolucion getTaGzzTipoDevolucion() {
        return this.taGzzTipoDevolucion;
    }
    
    public void setTaGzzTipoDevolucion(TaGzzTipoDevolucion taGzzTipoDevolucion) {
        this.taGzzTipoDevolucion = taGzzTipoDevolucion;
    }
    public String getDevVenDet() {
        return this.devVenDet;
    }
    
    public void setDevVenDet(String devVenDet) {
        this.devVenDet = devVenDet;
    }
    public Date getDevVenFec() {
        return this.devVenFec;
    }
    
    public void setDevVenFec(Date devVenFec) {
        this.devVenFec = devVenFec;
    }
    public double getDevVenMon() {
        return this.devVenMon;
    }
    
    public void setDevVenMon(double devVenMon) {
        this.devVenMon = devVenMon;
    }




}


