package org.epis.minierp.model;
// Generated 29/10/2016 12:36:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnP1mCatalogoRuta generated by hbm2java
 */
public class EnP1mCatalogoRuta  implements java.io.Serializable {


     private Integer catRutCod;
     private String catRutDet;
     private char estRegCod;
     private Set enP1mClientesRutases = new HashSet(0);

    public EnP1mCatalogoRuta() {
    }

	
    public EnP1mCatalogoRuta(String catRutDet, char estRegCod) {
        this.catRutDet = catRutDet;
        this.estRegCod = estRegCod;
    }
    public EnP1mCatalogoRuta(String catRutDet, char estRegCod, Set enP1mClientesRutases) {
       this.catRutDet = catRutDet;
       this.estRegCod = estRegCod;
       this.enP1mClientesRutases = enP1mClientesRutases;
    }
   
    public Integer getCatRutCod() {
        return this.catRutCod;
    }
    
    public void setCatRutCod(Integer catRutCod) {
        this.catRutCod = catRutCod;
    }
    public String getCatRutDet() {
        return this.catRutDet;
    }
    
    public void setCatRutDet(String catRutDet) {
        this.catRutDet = catRutDet;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP1mClientesRutases() {
        return this.enP1mClientesRutases;
    }
    
    public void setEnP1mClientesRutases(Set enP1mClientesRutases) {
        this.enP1mClientesRutases = enP1mClientesRutases;
    }




}


