package org.epis.minierp.model;
// Generated 26/02/2017 07:56:21 PM by Hibernate Tools 4.3.1



/**
 * EnP1mListaPreciosUsuariosId generated by hbm2java
 */
public class EnP1mListaPreciosUsuariosId  implements java.io.Serializable {


     private String usuCod;
     private int lisPreCod;

    public EnP1mListaPreciosUsuariosId() {
    }

    public EnP1mListaPreciosUsuariosId(String usuCod, int lisPreCod) {
       this.usuCod = usuCod;
       this.lisPreCod = lisPreCod;
    }
   
    public String getUsuCod() {
        return this.usuCod;
    }
    
    public void setUsuCod(String usuCod) {
        this.usuCod = usuCod;
    }
    public int getLisPreCod() {
        return this.lisPreCod;
    }
    
    public void setLisPreCod(int lisPreCod) {
        this.lisPreCod = lisPreCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnP1mListaPreciosUsuariosId) ) return false;
		 EnP1mListaPreciosUsuariosId castOther = ( EnP1mListaPreciosUsuariosId ) other; 
         
		 return ( (this.getUsuCod()==castOther.getUsuCod()) || ( this.getUsuCod()!=null && castOther.getUsuCod()!=null && this.getUsuCod().equals(castOther.getUsuCod()) ) )
 && (this.getLisPreCod()==castOther.getLisPreCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuCod() == null ? 0 : this.getUsuCod().hashCode() );
         result = 37 * result + this.getLisPreCod();
         return result;
   }   


}


