package org.epis.minierp.model;
// Generated 31/10/2016 01:37:15 AM by Hibernate Tools 4.3.1



/**
 * EnP1mMovimientoPuntoVenId generated by hbm2java
 */
public class EnP1mMovimientoPuntoVenId  implements java.io.Serializable {


     private int movPunVenCod;
     private int punVenCod;
     private int sucCod;

    public EnP1mMovimientoPuntoVenId() {
    }

    public EnP1mMovimientoPuntoVenId(int movPunVenCod, int punVenCod, int sucCod) {
       this.movPunVenCod = movPunVenCod;
       this.punVenCod = punVenCod;
       this.sucCod = sucCod;
    }
   
    public int getMovPunVenCod() {
        return this.movPunVenCod;
    }
    
    public void setMovPunVenCod(int movPunVenCod) {
        this.movPunVenCod = movPunVenCod;
    }
    public int getPunVenCod() {
        return this.punVenCod;
    }
    
    public void setPunVenCod(int punVenCod) {
        this.punVenCod = punVenCod;
    }
    public int getSucCod() {
        return this.sucCod;
    }
    
    public void setSucCod(int sucCod) {
        this.sucCod = sucCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnP1mMovimientoPuntoVenId) ) return false;
		 EnP1mMovimientoPuntoVenId castOther = ( EnP1mMovimientoPuntoVenId ) other; 
         
		 return (this.getMovPunVenCod()==castOther.getMovPunVenCod())
 && (this.getPunVenCod()==castOther.getPunVenCod())
 && (this.getSucCod()==castOther.getSucCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMovPunVenCod();
         result = 37 * result + this.getPunVenCod();
         result = 37 * result + this.getSucCod();
         return result;
   }   


}


