package org.epis.minierp.model;
// Generated 04/03/2017 10:43:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EnP1tFacturaVentaDet generated by hbm2java
 */
public class EnP1tFacturaVentaDet  implements java.io.Serializable {


     private EnP1tFacturaVentaDetId id;
     private EnP1mFacturaVentaCab enP1mFacturaVentaCab;
     private EnP2mProducto enP2mProducto;
     private BigDecimal facVenDetCan;
     private BigDecimal facVenDetValUni;

    public EnP1tFacturaVentaDet() {
    }

    public EnP1tFacturaVentaDet(EnP1tFacturaVentaDetId id, EnP1mFacturaVentaCab enP1mFacturaVentaCab, EnP2mProducto enP2mProducto, BigDecimal facVenDetCan, BigDecimal facVenDetValUni) {
       this.id = id;
       this.enP1mFacturaVentaCab = enP1mFacturaVentaCab;
       this.enP2mProducto = enP2mProducto;
       this.facVenDetCan = facVenDetCan;
       this.facVenDetValUni = facVenDetValUni;
    }
   
    public EnP1tFacturaVentaDetId getId() {
        return this.id;
    }
    
    public void setId(EnP1tFacturaVentaDetId id) {
        this.id = id;
    }
    public EnP1mFacturaVentaCab getEnP1mFacturaVentaCab() {
        return this.enP1mFacturaVentaCab;
    }
    
    public void setEnP1mFacturaVentaCab(EnP1mFacturaVentaCab enP1mFacturaVentaCab) {
        this.enP1mFacturaVentaCab = enP1mFacturaVentaCab;
    }
    public EnP2mProducto getEnP2mProducto() {
        return this.enP2mProducto;
    }
    
    public void setEnP2mProducto(EnP2mProducto enP2mProducto) {
        this.enP2mProducto = enP2mProducto;
    }
    public BigDecimal getFacVenDetCan() {
        return this.facVenDetCan;
    }
    
    public void setFacVenDetCan(BigDecimal facVenDetCan) {
        this.facVenDetCan = facVenDetCan;
    }
    public BigDecimal getFacVenDetValUni() {
        return this.facVenDetValUni;
    }
    
    public void setFacVenDetValUni(BigDecimal facVenDetValUni) {
        this.facVenDetValUni = facVenDetValUni;
    }




}


