package org.epis.minierp.model;
// Generated 25/11/2016 01:35:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnP1mEmpresa generated by hbm2java
 */
public class EnP1mEmpresa  implements java.io.Serializable {


     private Integer empCod;
     private String empRazSoc;
     private String empNomCom;
     private String empDomFis;
     private String empDes;
     private String empDir;
     private String empTel;
     private String empEmail;
     private double empIgv;
     private Double empTipCamCom;
     private Double empTipCamVen;
     private String empRuc;
     private Integer empLot;
     private String empImgUrl;
     private Set enP2mGuiaRemTransportistas = new HashSet(0);
     private Set enP2mGuiaRemRemitentes = new HashSet(0);

    public EnP1mEmpresa() {
    }

	
    public EnP1mEmpresa(String empRazSoc, String empNomCom, String empDir, double empIgv, String empRuc) {
        this.empRazSoc = empRazSoc;
        this.empNomCom = empNomCom;
        this.empDir = empDir;
        this.empIgv = empIgv;
        this.empRuc = empRuc;
    }
    public EnP1mEmpresa(String empRazSoc, String empNomCom, String empDomFis, String empDes, String empDir, String empTel, String empEmail, double empIgv, Double empTipCamCom, Double empTipCamVen, String empRuc, Integer empLot, String empImgUrl, Set enP2mGuiaRemTransportistas, Set enP2mGuiaRemRemitentes) {
       this.empRazSoc = empRazSoc;
       this.empNomCom = empNomCom;
       this.empDomFis = empDomFis;
       this.empDes = empDes;
       this.empDir = empDir;
       this.empTel = empTel;
       this.empEmail = empEmail;
       this.empIgv = empIgv;
       this.empTipCamCom = empTipCamCom;
       this.empTipCamVen = empTipCamVen;
       this.empRuc = empRuc;
       this.empLot = empLot;
       this.empImgUrl = empImgUrl;
       this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
       this.enP2mGuiaRemRemitentes = enP2mGuiaRemRemitentes;
    }
   
    public Integer getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(Integer empCod) {
        this.empCod = empCod;
    }
    public String getEmpRazSoc() {
        return this.empRazSoc;
    }
    
    public void setEmpRazSoc(String empRazSoc) {
        this.empRazSoc = empRazSoc;
    }
    public String getEmpNomCom() {
        return this.empNomCom;
    }
    
    public void setEmpNomCom(String empNomCom) {
        this.empNomCom = empNomCom;
    }
    public String getEmpDomFis() {
        return this.empDomFis;
    }
    
    public void setEmpDomFis(String empDomFis) {
        this.empDomFis = empDomFis;
    }
    public String getEmpDes() {
        return this.empDes;
    }
    
    public void setEmpDes(String empDes) {
        this.empDes = empDes;
    }
    public String getEmpDir() {
        return this.empDir;
    }
    
    public void setEmpDir(String empDir) {
        this.empDir = empDir;
    }
    public String getEmpTel() {
        return this.empTel;
    }
    
    public void setEmpTel(String empTel) {
        this.empTel = empTel;
    }
    public String getEmpEmail() {
        return this.empEmail;
    }
    
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }
    public double getEmpIgv() {
        return this.empIgv;
    }
    
    public void setEmpIgv(double empIgv) {
        this.empIgv = empIgv;
    }
    public Double getEmpTipCamCom() {
        return this.empTipCamCom;
    }
    
    public void setEmpTipCamCom(Double empTipCamCom) {
        this.empTipCamCom = empTipCamCom;
    }
    public Double getEmpTipCamVen() {
        return this.empTipCamVen;
    }
    
    public void setEmpTipCamVen(Double empTipCamVen) {
        this.empTipCamVen = empTipCamVen;
    }
    public String getEmpRuc() {
        return this.empRuc;
    }
    
    public void setEmpRuc(String empRuc) {
        this.empRuc = empRuc;
    }
    public Integer getEmpLot() {
        return this.empLot;
    }
    
    public void setEmpLot(Integer empLot) {
        this.empLot = empLot;
    }
    public String getEmpImgUrl() {
        return this.empImgUrl;
    }
    
    public void setEmpImgUrl(String empImgUrl) {
        this.empImgUrl = empImgUrl;
    }
    public Set getEnP2mGuiaRemTransportistas() {
        return this.enP2mGuiaRemTransportistas;
    }
    
    public void setEnP2mGuiaRemTransportistas(Set enP2mGuiaRemTransportistas) {
        this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
    }
    public Set getEnP2mGuiaRemRemitentes() {
        return this.enP2mGuiaRemRemitentes;
    }
    
    public void setEnP2mGuiaRemRemitentes(Set enP2mGuiaRemRemitentes) {
        this.enP2mGuiaRemRemitentes = enP2mGuiaRemRemitentes;
    }




}


