package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnP1mClientesRutas generated by hbm2java
 */
@Entity
@Table(name="en_p1m_clientes_rutas"
    ,catalog="episerp"
)
public class EnP1mClientesRutas  implements java.io.Serializable {


     private EnP1mClientesRutasId id;
     private EnP1mCatalogoRuta enP1mCatalogoRuta;
     private EnP1mCliente enP1mCliente;
     private String cliRutDes;
     private char estRegCod;

    public EnP1mClientesRutas() {
    }

    public EnP1mClientesRutas(EnP1mClientesRutasId id, EnP1mCatalogoRuta enP1mCatalogoRuta, EnP1mCliente enP1mCliente, String cliRutDes, char estRegCod) {
       this.id = id;
       this.enP1mCatalogoRuta = enP1mCatalogoRuta;
       this.enP1mCliente = enP1mCliente;
       this.cliRutDes = cliRutDes;
       this.estRegCod = estRegCod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="catRutCod", column=@Column(name="CatRutCod", nullable=false) ), 
        @AttributeOverride(name="cliCod", column=@Column(name="CliCod", nullable=false, length=15) ) } )
    public EnP1mClientesRutasId getId() {
        return this.id;
    }
    
    public void setId(EnP1mClientesRutasId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CatRutCod", nullable=false, insertable=false, updatable=false)
    public EnP1mCatalogoRuta getEnP1mCatalogoRuta() {
        return this.enP1mCatalogoRuta;
    }
    
    public void setEnP1mCatalogoRuta(EnP1mCatalogoRuta enP1mCatalogoRuta) {
        this.enP1mCatalogoRuta = enP1mCatalogoRuta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CliCod", nullable=false, insertable=false, updatable=false)
    public EnP1mCliente getEnP1mCliente() {
        return this.enP1mCliente;
    }
    
    public void setEnP1mCliente(EnP1mCliente enP1mCliente) {
        this.enP1mCliente = enP1mCliente;
    }

    
    @Column(name="CliRutDes", nullable=false, length=100)
    public String getCliRutDes() {
        return this.cliRutDes;
    }
    
    public void setCliRutDes(String cliRutDes) {
        this.cliRutDes = cliRutDes;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


