package org.epis.minierp.model;
// Generated 31/10/2016 01:37:15 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EnP1cDevolucionVentas generated by hbm2java
 */
public class EnP1cDevolucionVentas  implements java.io.Serializable {


     private String facVenCabCod;
     private EnP1mFacturaVentaCab enP1mFacturaVentaCab;
     private EnP2mGuiaRemRemitente enP2mGuiaRemRemitente;
     private EnP2mGuiaRemTransportista enP2mGuiaRemTransportista;
     private TaGzzTipoDevolucion taGzzTipoDevolucion;
     private String devVenDet;
     private Date devVenFec;
     private double devVenMon;

    public EnP1cDevolucionVentas() {
    }

	
    public EnP1cDevolucionVentas(EnP1mFacturaVentaCab enP1mFacturaVentaCab, Date devVenFec, double devVenMon) {
        this.enP1mFacturaVentaCab = enP1mFacturaVentaCab;
        this.devVenFec = devVenFec;
        this.devVenMon = devVenMon;
    }
    public EnP1cDevolucionVentas(EnP1mFacturaVentaCab enP1mFacturaVentaCab, EnP2mGuiaRemRemitente enP2mGuiaRemRemitente, EnP2mGuiaRemTransportista enP2mGuiaRemTransportista, TaGzzTipoDevolucion taGzzTipoDevolucion, String devVenDet, Date devVenFec, double devVenMon) {
       this.enP1mFacturaVentaCab = enP1mFacturaVentaCab;
       this.enP2mGuiaRemRemitente = enP2mGuiaRemRemitente;
       this.enP2mGuiaRemTransportista = enP2mGuiaRemTransportista;
       this.taGzzTipoDevolucion = taGzzTipoDevolucion;
       this.devVenDet = devVenDet;
       this.devVenFec = devVenFec;
       this.devVenMon = devVenMon;
    }
   
    public String getFacVenCabCod() {
        return this.facVenCabCod;
    }
    
    public void setFacVenCabCod(String facVenCabCod) {
        this.facVenCabCod = facVenCabCod;
    }
    public EnP1mFacturaVentaCab getEnP1mFacturaVentaCab() {
        return this.enP1mFacturaVentaCab;
    }
    
    public void setEnP1mFacturaVentaCab(EnP1mFacturaVentaCab enP1mFacturaVentaCab) {
        this.enP1mFacturaVentaCab = enP1mFacturaVentaCab;
    }
    public EnP2mGuiaRemRemitente getEnP2mGuiaRemRemitente() {
        return this.enP2mGuiaRemRemitente;
    }
    
    public void setEnP2mGuiaRemRemitente(EnP2mGuiaRemRemitente enP2mGuiaRemRemitente) {
        this.enP2mGuiaRemRemitente = enP2mGuiaRemRemitente;
    }
    public EnP2mGuiaRemTransportista getEnP2mGuiaRemTransportista() {
        return this.enP2mGuiaRemTransportista;
    }
    
    public void setEnP2mGuiaRemTransportista(EnP2mGuiaRemTransportista enP2mGuiaRemTransportista) {
        this.enP2mGuiaRemTransportista = enP2mGuiaRemTransportista;
    }
    public TaGzzTipoDevolucion getTaGzzTipoDevolucion() {
        return this.taGzzTipoDevolucion;
    }
    
    public void setTaGzzTipoDevolucion(TaGzzTipoDevolucion taGzzTipoDevolucion) {
        this.taGzzTipoDevolucion = taGzzTipoDevolucion;
    }
    public String getDevVenDet() {
        return this.devVenDet;
    }
    
    public void setDevVenDet(String devVenDet) {
        this.devVenDet = devVenDet;
    }
    public Date getDevVenFec() {
        return this.devVenFec;
    }
    
    public void setDevVenFec(Date devVenFec) {
        this.devVenFec = devVenFec;
    }
    public double getDevVenMon() {
        return this.devVenMon;
    }
    
    public void setDevVenMon(double devVenMon) {
        this.devVenMon = devVenMon;
    }




}


