package org.epis.minierp.model;
// Generated 31/10/2016 01:37:15 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EnP1mMovimientoPuntoVen generated by hbm2java
 */
public class EnP1mMovimientoPuntoVen  implements java.io.Serializable {


     private EnP1mMovimientoPuntoVenId id;
     private EnP1mPuntoVenta enP1mPuntoVenta;
     private EnP1mUsuario enP1mUsuario;
     private TaGzzTipoComprobante taGzzTipoComprobante;
     private String movPunVenComCod;
     private Date movPunVenFec;
     private Double movPunVenMon;
     private Character estRegCod;

    public EnP1mMovimientoPuntoVen() {
    }

	
    public EnP1mMovimientoPuntoVen(EnP1mMovimientoPuntoVenId id, EnP1mPuntoVenta enP1mPuntoVenta, EnP1mUsuario enP1mUsuario, String movPunVenComCod) {
        this.id = id;
        this.enP1mPuntoVenta = enP1mPuntoVenta;
        this.enP1mUsuario = enP1mUsuario;
        this.movPunVenComCod = movPunVenComCod;
    }
    public EnP1mMovimientoPuntoVen(EnP1mMovimientoPuntoVenId id, EnP1mPuntoVenta enP1mPuntoVenta, EnP1mUsuario enP1mUsuario, TaGzzTipoComprobante taGzzTipoComprobante, String movPunVenComCod, Date movPunVenFec, Double movPunVenMon, Character estRegCod) {
       this.id = id;
       this.enP1mPuntoVenta = enP1mPuntoVenta;
       this.enP1mUsuario = enP1mUsuario;
       this.taGzzTipoComprobante = taGzzTipoComprobante;
       this.movPunVenComCod = movPunVenComCod;
       this.movPunVenFec = movPunVenFec;
       this.movPunVenMon = movPunVenMon;
       this.estRegCod = estRegCod;
    }
   
    public EnP1mMovimientoPuntoVenId getId() {
        return this.id;
    }
    
    public void setId(EnP1mMovimientoPuntoVenId id) {
        this.id = id;
    }
    public EnP1mPuntoVenta getEnP1mPuntoVenta() {
        return this.enP1mPuntoVenta;
    }
    
    public void setEnP1mPuntoVenta(EnP1mPuntoVenta enP1mPuntoVenta) {
        this.enP1mPuntoVenta = enP1mPuntoVenta;
    }
    public EnP1mUsuario getEnP1mUsuario() {
        return this.enP1mUsuario;
    }
    
    public void setEnP1mUsuario(EnP1mUsuario enP1mUsuario) {
        this.enP1mUsuario = enP1mUsuario;
    }
    public TaGzzTipoComprobante getTaGzzTipoComprobante() {
        return this.taGzzTipoComprobante;
    }
    
    public void setTaGzzTipoComprobante(TaGzzTipoComprobante taGzzTipoComprobante) {
        this.taGzzTipoComprobante = taGzzTipoComprobante;
    }
    public String getMovPunVenComCod() {
        return this.movPunVenComCod;
    }
    
    public void setMovPunVenComCod(String movPunVenComCod) {
        this.movPunVenComCod = movPunVenComCod;
    }
    public Date getMovPunVenFec() {
        return this.movPunVenFec;
    }
    
    public void setMovPunVenFec(Date movPunVenFec) {
        this.movPunVenFec = movPunVenFec;
    }
    public Double getMovPunVenMon() {
        return this.movPunVenMon;
    }
    
    public void setMovPunVenMon(Double movPunVenMon) {
        this.movPunVenMon = movPunVenMon;
    }
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }




}


