package org.epis.minierp.model;
// Generated 04/03/2017 10:43:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EnP1tPagosCuotasDet generated by hbm2java
 */
public class EnP1tPagosCuotasDet  implements java.io.Serializable {


     private EnP1tPagosCuotasDetId id;
     private EnP1mPagosCuotasCab enP1mPagosCuotasCab;
     private BigDecimal pagCuoDetTotPag;

    public EnP1tPagosCuotasDet() {
    }

    public EnP1tPagosCuotasDet(EnP1tPagosCuotasDetId id, EnP1mPagosCuotasCab enP1mPagosCuotasCab, BigDecimal pagCuoDetTotPag) {
       this.id = id;
       this.enP1mPagosCuotasCab = enP1mPagosCuotasCab;
       this.pagCuoDetTotPag = pagCuoDetTotPag;
    }
   
    public EnP1tPagosCuotasDetId getId() {
        return this.id;
    }
    
    public void setId(EnP1tPagosCuotasDetId id) {
        this.id = id;
    }
    public EnP1mPagosCuotasCab getEnP1mPagosCuotasCab() {
        return this.enP1mPagosCuotasCab;
    }
    
    public void setEnP1mPagosCuotasCab(EnP1mPagosCuotasCab enP1mPagosCuotasCab) {
        this.enP1mPagosCuotasCab = enP1mPagosCuotasCab;
    }
    public BigDecimal getPagCuoDetTotPag() {
        return this.pagCuoDetTotPag;
    }
    
    public void setPagCuoDetTotPag(BigDecimal pagCuoDetTotPag) {
        this.pagCuoDetTotPag = pagCuoDetTotPag;
    }




}


