package org.epis.minierp.model;
// Generated 27/11/2016 05:44:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EnP2cDevolucionCompras generated by hbm2java
 */
public class EnP2cDevolucionCompras  implements java.io.Serializable {


     private String facComCabCod;
     private EnP4mFacturaCompraCab enP4mFacturaCompraCabByFacComCabCod;
     private EnP4mFacturaCompraCab enP4mFacturaCompraCabByDevComNewFac;
     private TaGzzTipoDevolucion taGzzTipoDevolucion;
     private String devComDet;
     private Date devComFec;
     private double devComMon;

    public EnP2cDevolucionCompras() {
    }

	
    public EnP2cDevolucionCompras(EnP4mFacturaCompraCab enP4mFacturaCompraCabByFacComCabCod, Date devComFec, double devComMon) {
        this.enP4mFacturaCompraCabByFacComCabCod = enP4mFacturaCompraCabByFacComCabCod;
        this.devComFec = devComFec;
        this.devComMon = devComMon;
    }
    public EnP2cDevolucionCompras(EnP4mFacturaCompraCab enP4mFacturaCompraCabByFacComCabCod, EnP4mFacturaCompraCab enP4mFacturaCompraCabByDevComNewFac, TaGzzTipoDevolucion taGzzTipoDevolucion, String devComDet, Date devComFec, double devComMon) {
       this.enP4mFacturaCompraCabByFacComCabCod = enP4mFacturaCompraCabByFacComCabCod;
       this.enP4mFacturaCompraCabByDevComNewFac = enP4mFacturaCompraCabByDevComNewFac;
       this.taGzzTipoDevolucion = taGzzTipoDevolucion;
       this.devComDet = devComDet;
       this.devComFec = devComFec;
       this.devComMon = devComMon;
    }
   
    public String getFacComCabCod() {
        return this.facComCabCod;
    }
    
    public void setFacComCabCod(String facComCabCod) {
        this.facComCabCod = facComCabCod;
    }
    public EnP4mFacturaCompraCab getEnP4mFacturaCompraCabByFacComCabCod() {
        return this.enP4mFacturaCompraCabByFacComCabCod;
    }
    
    public void setEnP4mFacturaCompraCabByFacComCabCod(EnP4mFacturaCompraCab enP4mFacturaCompraCabByFacComCabCod) {
        this.enP4mFacturaCompraCabByFacComCabCod = enP4mFacturaCompraCabByFacComCabCod;
    }
    public EnP4mFacturaCompraCab getEnP4mFacturaCompraCabByDevComNewFac() {
        return this.enP4mFacturaCompraCabByDevComNewFac;
    }
    
    public void setEnP4mFacturaCompraCabByDevComNewFac(EnP4mFacturaCompraCab enP4mFacturaCompraCabByDevComNewFac) {
        this.enP4mFacturaCompraCabByDevComNewFac = enP4mFacturaCompraCabByDevComNewFac;
    }
    public TaGzzTipoDevolucion getTaGzzTipoDevolucion() {
        return this.taGzzTipoDevolucion;
    }
    
    public void setTaGzzTipoDevolucion(TaGzzTipoDevolucion taGzzTipoDevolucion) {
        this.taGzzTipoDevolucion = taGzzTipoDevolucion;
    }
    public String getDevComDet() {
        return this.devComDet;
    }
    
    public void setDevComDet(String devComDet) {
        this.devComDet = devComDet;
    }
    public Date getDevComFec() {
        return this.devComFec;
    }
    
    public void setDevComFec(Date devComFec) {
        this.devComFec = devComFec;
    }
    public double getDevComMon() {
        return this.devComMon;
    }
    
    public void setDevComMon(double devComMon) {
        this.devComMon = devComMon;
    }




}


