package org.epis.minierp.model;
// Generated 26/02/2017 07:56:21 PM by Hibernate Tools 4.3.1



/**
 * EnP2mPrecioUnitarioId generated by hbm2java
 */
public class EnP2mPrecioUnitarioId  implements java.io.Serializable {


     private String proCod;
     private String subClaProCod;
     private String claProCod;
     private int lisPreCod;

    public EnP2mPrecioUnitarioId() {
    }

    public EnP2mPrecioUnitarioId(String proCod, String subClaProCod, String claProCod, int lisPreCod) {
       this.proCod = proCod;
       this.subClaProCod = subClaProCod;
       this.claProCod = claProCod;
       this.lisPreCod = lisPreCod;
    }
   
    public String getProCod() {
        return this.proCod;
    }
    
    public void setProCod(String proCod) {
        this.proCod = proCod;
    }
    public String getSubClaProCod() {
        return this.subClaProCod;
    }
    
    public void setSubClaProCod(String subClaProCod) {
        this.subClaProCod = subClaProCod;
    }
    public String getClaProCod() {
        return this.claProCod;
    }
    
    public void setClaProCod(String claProCod) {
        this.claProCod = claProCod;
    }
    public int getLisPreCod() {
        return this.lisPreCod;
    }
    
    public void setLisPreCod(int lisPreCod) {
        this.lisPreCod = lisPreCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnP2mPrecioUnitarioId) ) return false;
		 EnP2mPrecioUnitarioId castOther = ( EnP2mPrecioUnitarioId ) other; 
         
		 return ( (this.getProCod()==castOther.getProCod()) || ( this.getProCod()!=null && castOther.getProCod()!=null && this.getProCod().equals(castOther.getProCod()) ) )
 && ( (this.getSubClaProCod()==castOther.getSubClaProCod()) || ( this.getSubClaProCod()!=null && castOther.getSubClaProCod()!=null && this.getSubClaProCod().equals(castOther.getSubClaProCod()) ) )
 && ( (this.getClaProCod()==castOther.getClaProCod()) || ( this.getClaProCod()!=null && castOther.getClaProCod()!=null && this.getClaProCod().equals(castOther.getClaProCod()) ) )
 && (this.getLisPreCod()==castOther.getLisPreCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProCod() == null ? 0 : this.getProCod().hashCode() );
         result = 37 * result + ( getSubClaProCod() == null ? 0 : this.getSubClaProCod().hashCode() );
         result = 37 * result + ( getClaProCod() == null ? 0 : this.getClaProCod().hashCode() );
         result = 37 * result + this.getLisPreCod();
         return result;
   }   


}


