package org.epis.minierp.model;
// Generated 28/10/2016 01:30:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnP2mAlmacen generated by hbm2java
 */
public class EnP2mAlmacen  implements java.io.Serializable {


     private String almCod;
     private EnP1mSucursal enP1mSucursal;
     private String almDet;
     private Double almVolTot;
     private String almObs;
     private char estRegCod;
     private Set enP2mProductos = new HashSet(0);

    public EnP2mAlmacen() {
    }

	
    public EnP2mAlmacen(String almCod, EnP1mSucursal enP1mSucursal, String almObs, char estRegCod) {
        this.almCod = almCod;
        this.enP1mSucursal = enP1mSucursal;
        this.almObs = almObs;
        this.estRegCod = estRegCod;
    }
    public EnP2mAlmacen(String almCod, EnP1mSucursal enP1mSucursal, String almDet, Double almVolTot, String almObs, char estRegCod, Set enP2mProductos) {
       this.almCod = almCod;
       this.enP1mSucursal = enP1mSucursal;
       this.almDet = almDet;
       this.almVolTot = almVolTot;
       this.almObs = almObs;
       this.estRegCod = estRegCod;
       this.enP2mProductos = enP2mProductos;
    }
   
    public String getAlmCod() {
        return this.almCod;
    }
    
    public void setAlmCod(String almCod) {
        this.almCod = almCod;
    }
    public EnP1mSucursal getEnP1mSucursal() {
        return this.enP1mSucursal;
    }
    
    public void setEnP1mSucursal(EnP1mSucursal enP1mSucursal) {
        this.enP1mSucursal = enP1mSucursal;
    }
    public String getAlmDet() {
        return this.almDet;
    }
    
    public void setAlmDet(String almDet) {
        this.almDet = almDet;
    }
    public Double getAlmVolTot() {
        return this.almVolTot;
    }
    
    public void setAlmVolTot(Double almVolTot) {
        this.almVolTot = almVolTot;
    }
    public String getAlmObs() {
        return this.almObs;
    }
    
    public void setAlmObs(String almObs) {
        this.almObs = almObs;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP2mProductos() {
        return this.enP2mProductos;
    }
    
    public void setEnP2mProductos(Set enP2mProductos) {
        this.enP2mProductos = enP2mProductos;
    }




}


