package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnP2tInventarioDet generated by hbm2java
 */
@Entity
@Table(name="en_p2t_inventario_det"
    ,catalog="episerp"
)
public class EnP2tInventarioDet  implements java.io.Serializable {


     private EnP2tInventarioDetId id;
     private EnP2mInventarioCab enP2mInventarioCab;
     private EnP2mProducto enP2mProducto;
     private double invDetDifStk;

    public EnP2tInventarioDet() {
    }

	
    public EnP2tInventarioDet(EnP2tInventarioDetId id, EnP2mInventarioCab enP2mInventarioCab, double invDetDifStk) {
        this.id = id;
        this.enP2mInventarioCab = enP2mInventarioCab;
        this.invDetDifStk = invDetDifStk;
    }
    public EnP2tInventarioDet(EnP2tInventarioDetId id, EnP2mInventarioCab enP2mInventarioCab, EnP2mProducto enP2mProducto, double invDetDifStk) {
       this.id = id;
       this.enP2mInventarioCab = enP2mInventarioCab;
       this.enP2mProducto = enP2mProducto;
       this.invDetDifStk = invDetDifStk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="invDetCod", column=@Column(name="InvDetCod", nullable=false) ), 
        @AttributeOverride(name="invCabCod", column=@Column(name="InvCabCod", nullable=false, length=15) ) } )
    public EnP2tInventarioDetId getId() {
        return this.id;
    }
    
    public void setId(EnP2tInventarioDetId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="InvCabCod", nullable=false, insertable=false, updatable=false)
    public EnP2mInventarioCab getEnP2mInventarioCab() {
        return this.enP2mInventarioCab;
    }
    
    public void setEnP2mInventarioCab(EnP2mInventarioCab enP2mInventarioCab) {
        this.enP2mInventarioCab = enP2mInventarioCab;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ProCod", referencedColumnName="ProCod"), 
        @JoinColumn(name="SubClaProCod", referencedColumnName="SubClaProCod"), 
        @JoinColumn(name="ClaProCod", referencedColumnName="ClaProCod") } )
    public EnP2mProducto getEnP2mProducto() {
        return this.enP2mProducto;
    }
    
    public void setEnP2mProducto(EnP2mProducto enP2mProducto) {
        this.enP2mProducto = enP2mProducto;
    }

    
    @Column(name="InvDetDifStk", nullable=false, precision=10)
    public double getInvDetDifStk() {
        return this.invDetDifStk;
    }
    
    public void setInvDetDifStk(double invDetDifStk) {
        this.invDetDifStk = invDetDifStk;
    }




}


