package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnP2mTransportista generated by hbm2java
 */
@Entity
@Table(name="en_p2m_transportista"
    ,catalog="episerp"
)
public class EnP2mTransportista  implements java.io.Serializable {


     private String traCod;
     private String traNom;
     private String traApePat;
     private String traApeMat;
     private String traRazSoc;
     private String traNomCom;
     private String traDomFis;
     private String traTel;
     private String traEmail;
     private String traDir;
     private char estRegCod;
     private Set enP2mGuiaRemTransportistas = new HashSet(0);
     private Set enP2mDocumentoTransportistas = new HashSet(0);

    public EnP2mTransportista() {
    }

	
    public EnP2mTransportista(String traCod, String traNom, String traApePat, String traApeMat, char estRegCod) {
        this.traCod = traCod;
        this.traNom = traNom;
        this.traApePat = traApePat;
        this.traApeMat = traApeMat;
        this.estRegCod = estRegCod;
    }
    public EnP2mTransportista(String traCod, String traNom, String traApePat, String traApeMat, String traRazSoc, String traNomCom, String traDomFis, String traTel, String traEmail, String traDir, char estRegCod, Set enP2mGuiaRemTransportistas, Set enP2mDocumentoTransportistas) {
       this.traCod = traCod;
       this.traNom = traNom;
       this.traApePat = traApePat;
       this.traApeMat = traApeMat;
       this.traRazSoc = traRazSoc;
       this.traNomCom = traNomCom;
       this.traDomFis = traDomFis;
       this.traTel = traTel;
       this.traEmail = traEmail;
       this.traDir = traDir;
       this.estRegCod = estRegCod;
       this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
       this.enP2mDocumentoTransportistas = enP2mDocumentoTransportistas;
    }
   
     @Id 

    
    @Column(name="TraCod", unique=true, nullable=false, length=15)
    public String getTraCod() {
        return this.traCod;
    }
    
    public void setTraCod(String traCod) {
        this.traCod = traCod;
    }

    
    @Column(name="TraNom", nullable=false, length=90)
    public String getTraNom() {
        return this.traNom;
    }
    
    public void setTraNom(String traNom) {
        this.traNom = traNom;
    }

    
    @Column(name="TraApePat", nullable=false, length=90)
    public String getTraApePat() {
        return this.traApePat;
    }
    
    public void setTraApePat(String traApePat) {
        this.traApePat = traApePat;
    }

    
    @Column(name="TraApeMat", nullable=false, length=90)
    public String getTraApeMat() {
        return this.traApeMat;
    }
    
    public void setTraApeMat(String traApeMat) {
        this.traApeMat = traApeMat;
    }

    
    @Column(name="TraRazSoc", length=90)
    public String getTraRazSoc() {
        return this.traRazSoc;
    }
    
    public void setTraRazSoc(String traRazSoc) {
        this.traRazSoc = traRazSoc;
    }

    
    @Column(name="TraNomCom", length=90)
    public String getTraNomCom() {
        return this.traNomCom;
    }
    
    public void setTraNomCom(String traNomCom) {
        this.traNomCom = traNomCom;
    }

    
    @Column(name="TraDomFis", length=90)
    public String getTraDomFis() {
        return this.traDomFis;
    }
    
    public void setTraDomFis(String traDomFis) {
        this.traDomFis = traDomFis;
    }

    
    @Column(name="TraTel", length=20)
    public String getTraTel() {
        return this.traTel;
    }
    
    public void setTraTel(String traTel) {
        this.traTel = traTel;
    }

    
    @Column(name="TraEmail", length=50)
    public String getTraEmail() {
        return this.traEmail;
    }
    
    public void setTraEmail(String traEmail) {
        this.traEmail = traEmail;
    }

    
    @Column(name="TraDir", length=90)
    public String getTraDir() {
        return this.traDir;
    }
    
    public void setTraDir(String traDir) {
        this.traDir = traDir;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enP2mTransportista")
    public Set getEnP2mGuiaRemTransportistas() {
        return this.enP2mGuiaRemTransportistas;
    }
    
    public void setEnP2mGuiaRemTransportistas(Set enP2mGuiaRemTransportistas) {
        this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enP2mTransportista")
    public Set getEnP2mDocumentoTransportistas() {
        return this.enP2mDocumentoTransportistas;
    }
    
    public void setEnP2mDocumentoTransportistas(Set enP2mDocumentoTransportistas) {
        this.enP2mDocumentoTransportistas = enP2mDocumentoTransportistas;
    }




}


