package org.epis.minierp.model;
// Generated 04/03/2017 10:43:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * EnP2mCombos generated by hbm2java
 */
public class EnP2mCombos  implements java.io.Serializable {


     private String comCod;
     private String comDet;
     private BigDecimal comTot;
     private Character estRegCod;
     private Set enP2mComboDets = new HashSet(0);

    public EnP2mCombos() {
    }

	
    public EnP2mCombos(String comCod) {
        this.comCod = comCod;
    }
    public EnP2mCombos(String comCod, String comDet, BigDecimal comTot, Character estRegCod, Set enP2mComboDets) {
       this.comCod = comCod;
       this.comDet = comDet;
       this.comTot = comTot;
       this.estRegCod = estRegCod;
       this.enP2mComboDets = enP2mComboDets;
    }
   
    public String getComCod() {
        return this.comCod;
    }
    
    public void setComCod(String comCod) {
        this.comCod = comCod;
    }
    public String getComDet() {
        return this.comDet;
    }
    
    public void setComDet(String comDet) {
        this.comDet = comDet;
    }
    public BigDecimal getComTot() {
        return this.comTot;
    }
    
    public void setComTot(BigDecimal comTot) {
        this.comTot = comTot;
    }
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP2mComboDets() {
        return this.enP2mComboDets;
    }
    
    public void setEnP2mComboDets(Set enP2mComboDets) {
        this.enP2mComboDets = enP2mComboDets;
    }




}


