package org.epis.minierp.model;
// Generated 29/10/2016 12:36:12 PM by Hibernate Tools 4.3.1



/**
 * EnP2mAlmacen generated by hbm2java
 */
public class EnP2mAlmacen  implements java.io.Serializable {


     private String almCod;
     private EnP1mSucursal enP1mSucursal;
     private String almDet;
     private Double almVolTot;
     private String almObs;
     private char estRegCod;

    public EnP2mAlmacen() {
    }

	
    public EnP2mAlmacen(String almCod, EnP1mSucursal enP1mSucursal, String almObs, char estRegCod) {
        this.almCod = almCod;
        this.enP1mSucursal = enP1mSucursal;
        this.almObs = almObs;
        this.estRegCod = estRegCod;
    }
    public EnP2mAlmacen(String almCod, EnP1mSucursal enP1mSucursal, String almDet, Double almVolTot, String almObs, char estRegCod) {
       this.almCod = almCod;
       this.enP1mSucursal = enP1mSucursal;
       this.almDet = almDet;
       this.almVolTot = almVolTot;
       this.almObs = almObs;
       this.estRegCod = estRegCod;
    }
   
    public String getAlmCod() {
        return this.almCod;
    }
    
    public void setAlmCod(String almCod) {
        this.almCod = almCod;
    }
    public EnP1mSucursal getEnP1mSucursal() {
        return this.enP1mSucursal;
    }
    
    public void setEnP1mSucursal(EnP1mSucursal enP1mSucursal) {
        this.enP1mSucursal = enP1mSucursal;
    }
    public String getAlmDet() {
        return this.almDet;
    }
    
    public void setAlmDet(String almDet) {
        this.almDet = almDet;
    }
    public Double getAlmVolTot() {
        return this.almVolTot;
    }
    
    public void setAlmVolTot(Double almVolTot) {
        this.almVolTot = almVolTot;
    }
    public String getAlmObs() {
        return this.almObs;
    }
    
    public void setAlmObs(String almObs) {
        this.almObs = almObs;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


