package org.epis.minierp.model;
// Generated 27/11/2016 02:57:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnP2mSubclaseProducto generated by hbm2java
 */
public class EnP2mSubclaseProducto  implements java.io.Serializable {


     private EnP2mSubclaseProductoId id;
     private EnP2mClaseProducto enP2mClaseProducto;
     private EnP3mCuenta enP3mCuenta;
     private String subClaProDet;
     private char estRegCod;
     private Set enP2mProductos = new HashSet(0);

    public EnP2mSubclaseProducto() {
    }

	
    public EnP2mSubclaseProducto(EnP2mSubclaseProductoId id, EnP2mClaseProducto enP2mClaseProducto, String subClaProDet, char estRegCod) {
        this.id = id;
        this.enP2mClaseProducto = enP2mClaseProducto;
        this.subClaProDet = subClaProDet;
        this.estRegCod = estRegCod;
    }
    public EnP2mSubclaseProducto(EnP2mSubclaseProductoId id, EnP2mClaseProducto enP2mClaseProducto, EnP3mCuenta enP3mCuenta, String subClaProDet, char estRegCod, Set enP2mProductos) {
       this.id = id;
       this.enP2mClaseProducto = enP2mClaseProducto;
       this.enP3mCuenta = enP3mCuenta;
       this.subClaProDet = subClaProDet;
       this.estRegCod = estRegCod;
       this.enP2mProductos = enP2mProductos;
    }
   
    public EnP2mSubclaseProductoId getId() {
        return this.id;
    }
    
    public void setId(EnP2mSubclaseProductoId id) {
        this.id = id;
    }
    public EnP2mClaseProducto getEnP2mClaseProducto() {
        return this.enP2mClaseProducto;
    }
    
    public void setEnP2mClaseProducto(EnP2mClaseProducto enP2mClaseProducto) {
        this.enP2mClaseProducto = enP2mClaseProducto;
    }
    public EnP3mCuenta getEnP3mCuenta() {
        return this.enP3mCuenta;
    }
    
    public void setEnP3mCuenta(EnP3mCuenta enP3mCuenta) {
        this.enP3mCuenta = enP3mCuenta;
    }
    public String getSubClaProDet() {
        return this.subClaProDet;
    }
    
    public void setSubClaProDet(String subClaProDet) {
        this.subClaProDet = subClaProDet;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP2mProductos() {
        return this.enP2mProductos;
    }
    
    public void setEnP2mProductos(Set enP2mProductos) {
        this.enP2mProductos = enP2mProductos;
    }




}


