package org.epis.minierp.model;
// Generated 27/11/2016 05:44:55 PM by Hibernate Tools 4.3.1



/**
 * EnP2tInventarioDet generated by hbm2java
 */
public class EnP2tInventarioDet  implements java.io.Serializable {


     private EnP2tInventarioDetId id;
     private EnP2mInventarioCab enP2mInventarioCab;
     private EnP2mProducto enP2mProducto;
     private TaGzzTipoFallaProducto taGzzTipoFallaProducto;
     private double invDetDifStk;

    public EnP2tInventarioDet() {
    }

	
    public EnP2tInventarioDet(EnP2tInventarioDetId id, EnP2mInventarioCab enP2mInventarioCab, double invDetDifStk) {
        this.id = id;
        this.enP2mInventarioCab = enP2mInventarioCab;
        this.invDetDifStk = invDetDifStk;
    }
    public EnP2tInventarioDet(EnP2tInventarioDetId id, EnP2mInventarioCab enP2mInventarioCab, EnP2mProducto enP2mProducto, TaGzzTipoFallaProducto taGzzTipoFallaProducto, double invDetDifStk) {
       this.id = id;
       this.enP2mInventarioCab = enP2mInventarioCab;
       this.enP2mProducto = enP2mProducto;
       this.taGzzTipoFallaProducto = taGzzTipoFallaProducto;
       this.invDetDifStk = invDetDifStk;
    }
   
    public EnP2tInventarioDetId getId() {
        return this.id;
    }
    
    public void setId(EnP2tInventarioDetId id) {
        this.id = id;
    }
    public EnP2mInventarioCab getEnP2mInventarioCab() {
        return this.enP2mInventarioCab;
    }
    
    public void setEnP2mInventarioCab(EnP2mInventarioCab enP2mInventarioCab) {
        this.enP2mInventarioCab = enP2mInventarioCab;
    }
    public EnP2mProducto getEnP2mProducto() {
        return this.enP2mProducto;
    }
    
    public void setEnP2mProducto(EnP2mProducto enP2mProducto) {
        this.enP2mProducto = enP2mProducto;
    }
    public TaGzzTipoFallaProducto getTaGzzTipoFallaProducto() {
        return this.taGzzTipoFallaProducto;
    }
    
    public void setTaGzzTipoFallaProducto(TaGzzTipoFallaProducto taGzzTipoFallaProducto) {
        this.taGzzTipoFallaProducto = taGzzTipoFallaProducto;
    }
    public double getInvDetDifStk() {
        return this.invDetDifStk;
    }
    
    public void setInvDetDifStk(double invDetDifStk) {
        this.invDetDifStk = invDetDifStk;
    }




}


