package org.epis.minierp.model;
// Generated 04/03/2017 10:43:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EnP2mPrecioUnitario generated by hbm2java
 */
public class EnP2mPrecioUnitario  implements java.io.Serializable {


     private EnP2mPrecioUnitarioId id;
     private EnP2mProducto enP2mProducto;
     private TaGzzListaPrecios taGzzListaPrecios;
     private BigDecimal preUniVen;
     private BigDecimal preUniCom;
     private BigDecimal preUniMar;
     private BigDecimal preUniFle;

    public EnP2mPrecioUnitario() {
    }

	
    public EnP2mPrecioUnitario(EnP2mPrecioUnitarioId id, EnP2mProducto enP2mProducto, TaGzzListaPrecios taGzzListaPrecios, BigDecimal preUniVen) {
        this.id = id;
        this.enP2mProducto = enP2mProducto;
        this.taGzzListaPrecios = taGzzListaPrecios;
        this.preUniVen = preUniVen;
    }
    public EnP2mPrecioUnitario(EnP2mPrecioUnitarioId id, EnP2mProducto enP2mProducto, TaGzzListaPrecios taGzzListaPrecios, BigDecimal preUniVen, BigDecimal preUniCom, BigDecimal preUniMar, BigDecimal preUniFle) {
       this.id = id;
       this.enP2mProducto = enP2mProducto;
       this.taGzzListaPrecios = taGzzListaPrecios;
       this.preUniVen = preUniVen;
       this.preUniCom = preUniCom;
       this.preUniMar = preUniMar;
       this.preUniFle = preUniFle;
    }
   
    public EnP2mPrecioUnitarioId getId() {
        return this.id;
    }
    
    public void setId(EnP2mPrecioUnitarioId id) {
        this.id = id;
    }
    public EnP2mProducto getEnP2mProducto() {
        return this.enP2mProducto;
    }
    
    public void setEnP2mProducto(EnP2mProducto enP2mProducto) {
        this.enP2mProducto = enP2mProducto;
    }
    public TaGzzListaPrecios getTaGzzListaPrecios() {
        return this.taGzzListaPrecios;
    }
    
    public void setTaGzzListaPrecios(TaGzzListaPrecios taGzzListaPrecios) {
        this.taGzzListaPrecios = taGzzListaPrecios;
    }
    public BigDecimal getPreUniVen() {
        return this.preUniVen;
    }
    
    public void setPreUniVen(BigDecimal preUniVen) {
        this.preUniVen = preUniVen;
    }
    public BigDecimal getPreUniCom() {
        return this.preUniCom;
    }
    
    public void setPreUniCom(BigDecimal preUniCom) {
        this.preUniCom = preUniCom;
    }
    public BigDecimal getPreUniMar() {
        return this.preUniMar;
    }
    
    public void setPreUniMar(BigDecimal preUniMar) {
        this.preUniMar = preUniMar;
    }
    public BigDecimal getPreUniFle() {
        return this.preUniFle;
    }
    
    public void setPreUniFle(BigDecimal preUniFle) {
        this.preUniFle = preUniFle;
    }




}


