package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnP2mInventarioCab generated by hbm2java
 */
@Entity
@Table(name="en_p2m_inventario_cab"
    ,catalog="episerp"
)
public class EnP2mInventarioCab  implements java.io.Serializable {


     private String invCabCod;
     private EnP1mUsuario enP1mUsuario;
     private Date invCabFec;
     private boolean invCabEst;
     private char estRegCod;
     private Set enP2tInventarioDets = new HashSet(0);

    public EnP2mInventarioCab() {
    }

	
    public EnP2mInventarioCab(String invCabCod, Date invCabFec, boolean invCabEst, char estRegCod) {
        this.invCabCod = invCabCod;
        this.invCabFec = invCabFec;
        this.invCabEst = invCabEst;
        this.estRegCod = estRegCod;
    }
    public EnP2mInventarioCab(String invCabCod, EnP1mUsuario enP1mUsuario, Date invCabFec, boolean invCabEst, char estRegCod, Set enP2tInventarioDets) {
       this.invCabCod = invCabCod;
       this.enP1mUsuario = enP1mUsuario;
       this.invCabFec = invCabFec;
       this.invCabEst = invCabEst;
       this.estRegCod = estRegCod;
       this.enP2tInventarioDets = enP2tInventarioDets;
    }
   
     @Id 

    
    @Column(name="InvCabCod", unique=true, nullable=false, length=15)
    public String getInvCabCod() {
        return this.invCabCod;
    }
    
    public void setInvCabCod(String invCabCod) {
        this.invCabCod = invCabCod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UsuCod")
    public EnP1mUsuario getEnP1mUsuario() {
        return this.enP1mUsuario;
    }
    
    public void setEnP1mUsuario(EnP1mUsuario enP1mUsuario) {
        this.enP1mUsuario = enP1mUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="InvCabFec", nullable=false, length=10)
    public Date getInvCabFec() {
        return this.invCabFec;
    }
    
    public void setInvCabFec(Date invCabFec) {
        this.invCabFec = invCabFec;
    }

    
    @Column(name="InvCabEst", nullable=false)
    public boolean isInvCabEst() {
        return this.invCabEst;
    }
    
    public void setInvCabEst(boolean invCabEst) {
        this.invCabEst = invCabEst;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enP2mInventarioCab")
    public Set getEnP2tInventarioDets() {
        return this.enP2tInventarioDets;
    }
    
    public void setEnP2tInventarioDets(Set enP2tInventarioDets) {
        this.enP2tInventarioDets = enP2tInventarioDets;
    }




}


