package org.epis.minierp.model;
// Generated 04/03/2017 10:43:21 PM by Hibernate Tools 4.3.1



/**
 * EnP2mComboDet generated by hbm2java
 */
public class EnP2mComboDet  implements java.io.Serializable {


     private EnP2mComboDetId id;
     private EnP2mCombos enP2mCombos;
     private EnP2mProducto enP2mProducto;
     private Double comDetCan;

    public EnP2mComboDet() {
    }

	
    public EnP2mComboDet(EnP2mComboDetId id, EnP2mCombos enP2mCombos, EnP2mProducto enP2mProducto) {
        this.id = id;
        this.enP2mCombos = enP2mCombos;
        this.enP2mProducto = enP2mProducto;
    }
    public EnP2mComboDet(EnP2mComboDetId id, EnP2mCombos enP2mCombos, EnP2mProducto enP2mProducto, Double comDetCan) {
       this.id = id;
       this.enP2mCombos = enP2mCombos;
       this.enP2mProducto = enP2mProducto;
       this.comDetCan = comDetCan;
    }
   
    public EnP2mComboDetId getId() {
        return this.id;
    }
    
    public void setId(EnP2mComboDetId id) {
        this.id = id;
    }
    public EnP2mCombos getEnP2mCombos() {
        return this.enP2mCombos;
    }
    
    public void setEnP2mCombos(EnP2mCombos enP2mCombos) {
        this.enP2mCombos = enP2mCombos;
    }
    public EnP2mProducto getEnP2mProducto() {
        return this.enP2mProducto;
    }
    
    public void setEnP2mProducto(EnP2mProducto enP2mProducto) {
        this.enP2mProducto = enP2mProducto;
    }
    public Double getComDetCan() {
        return this.comDetCan;
    }
    
    public void setComDetCan(Double comDetCan) {
        this.comDetCan = comDetCan;
    }




}


