package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnP2mDocumentoTransportista generated by hbm2java
 */
@Entity
@Table(name="en_p2m_documento_transportista"
    ,catalog="episerp"
)
public class EnP2mDocumentoTransportista  implements java.io.Serializable {


     private EnP2mDocumentoTransportistaId id;
     private EnP2mTransportista enP2mTransportista;
     private TaGzzTipoDocTransportista taGzzTipoDocTransportista;
     private String docTraNum;
     private char estRegCod;

    public EnP2mDocumentoTransportista() {
    }

    public EnP2mDocumentoTransportista(EnP2mDocumentoTransportistaId id, EnP2mTransportista enP2mTransportista, TaGzzTipoDocTransportista taGzzTipoDocTransportista, String docTraNum, char estRegCod) {
       this.id = id;
       this.enP2mTransportista = enP2mTransportista;
       this.taGzzTipoDocTransportista = taGzzTipoDocTransportista;
       this.docTraNum = docTraNum;
       this.estRegCod = estRegCod;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tipDocTraCod", column=@Column(name="TipDocTraCod", nullable=false) ), 
        @AttributeOverride(name="traCod", column=@Column(name="TraCod", nullable=false, length=15) ) } )
    public EnP2mDocumentoTransportistaId getId() {
        return this.id;
    }
    
    public void setId(EnP2mDocumentoTransportistaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TraCod", nullable=false, insertable=false, updatable=false)
    public EnP2mTransportista getEnP2mTransportista() {
        return this.enP2mTransportista;
    }
    
    public void setEnP2mTransportista(EnP2mTransportista enP2mTransportista) {
        this.enP2mTransportista = enP2mTransportista;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TipDocTraCod", nullable=false, insertable=false, updatable=false)
    public TaGzzTipoDocTransportista getTaGzzTipoDocTransportista() {
        return this.taGzzTipoDocTransportista;
    }
    
    public void setTaGzzTipoDocTransportista(TaGzzTipoDocTransportista taGzzTipoDocTransportista) {
        this.taGzzTipoDocTransportista = taGzzTipoDocTransportista;
    }

    
    @Column(name="DocTraNum", nullable=false, length=30)
    public String getDocTraNum() {
        return this.docTraNum;
    }
    
    public void setDocTraNum(String docTraNum) {
        this.docTraNum = docTraNum;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


