package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnP2mUnidadTransporte generated by hbm2java
 */
@Entity
@Table(name="en_p2m_unidad_transporte"
    ,catalog="episerp"
)
public class EnP2mUnidadTransporte  implements java.io.Serializable {


     private String uniTraCod;
     private TaGzzEstadoUniTransporte taGzzEstadoUniTransporte;
     private TaGzzTipoUniTransporte taGzzTipoUniTransporte;
     private String uniTraMod;
     private String uniTraMar;
     private Double uniTraPes;
     private String uniTraNumPla;
     private char estRegCod;
     private Set enP2mGuiaRemTransportistas = new HashSet(0);

    public EnP2mUnidadTransporte() {
    }

	
    public EnP2mUnidadTransporte(String uniTraCod, String uniTraNumPla, char estRegCod) {
        this.uniTraCod = uniTraCod;
        this.uniTraNumPla = uniTraNumPla;
        this.estRegCod = estRegCod;
    }
    public EnP2mUnidadTransporte(String uniTraCod, TaGzzEstadoUniTransporte taGzzEstadoUniTransporte, TaGzzTipoUniTransporte taGzzTipoUniTransporte, String uniTraMod, String uniTraMar, Double uniTraPes, String uniTraNumPla, char estRegCod, Set enP2mGuiaRemTransportistas) {
       this.uniTraCod = uniTraCod;
       this.taGzzEstadoUniTransporte = taGzzEstadoUniTransporte;
       this.taGzzTipoUniTransporte = taGzzTipoUniTransporte;
       this.uniTraMod = uniTraMod;
       this.uniTraMar = uniTraMar;
       this.uniTraPes = uniTraPes;
       this.uniTraNumPla = uniTraNumPla;
       this.estRegCod = estRegCod;
       this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
    }
   
     @Id 

    
    @Column(name="UniTraCod", unique=true, nullable=false, length=15)
    public String getUniTraCod() {
        return this.uniTraCod;
    }
    
    public void setUniTraCod(String uniTraCod) {
        this.uniTraCod = uniTraCod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EstUniTraCod")
    public TaGzzEstadoUniTransporte getTaGzzEstadoUniTransporte() {
        return this.taGzzEstadoUniTransporte;
    }
    
    public void setTaGzzEstadoUniTransporte(TaGzzEstadoUniTransporte taGzzEstadoUniTransporte) {
        this.taGzzEstadoUniTransporte = taGzzEstadoUniTransporte;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TipUniTraCod")
    public TaGzzTipoUniTransporte getTaGzzTipoUniTransporte() {
        return this.taGzzTipoUniTransporte;
    }
    
    public void setTaGzzTipoUniTransporte(TaGzzTipoUniTransporte taGzzTipoUniTransporte) {
        this.taGzzTipoUniTransporte = taGzzTipoUniTransporte;
    }

    
    @Column(name="UniTraMod", length=50)
    public String getUniTraMod() {
        return this.uniTraMod;
    }
    
    public void setUniTraMod(String uniTraMod) {
        this.uniTraMod = uniTraMod;
    }

    
    @Column(name="UniTraMar", length=50)
    public String getUniTraMar() {
        return this.uniTraMar;
    }
    
    public void setUniTraMar(String uniTraMar) {
        this.uniTraMar = uniTraMar;
    }

    
    @Column(name="UniTraPes", precision=10)
    public Double getUniTraPes() {
        return this.uniTraPes;
    }
    
    public void setUniTraPes(Double uniTraPes) {
        this.uniTraPes = uniTraPes;
    }

    
    @Column(name="UniTraNumPla", nullable=false, length=20)
    public String getUniTraNumPla() {
        return this.uniTraNumPla;
    }
    
    public void setUniTraNumPla(String uniTraNumPla) {
        this.uniTraNumPla = uniTraNumPla;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enP2mUnidadTransporte")
    public Set getEnP2mGuiaRemTransportistas() {
        return this.enP2mGuiaRemTransportistas;
    }
    
    public void setEnP2mGuiaRemTransportistas(Set enP2mGuiaRemTransportistas) {
        this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
    }




}


