package org.epis.minierp.model;
// Generated 30/10/2016 12:40:40 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EnP3mAsientoCab generated by hbm2java
 */
public class EnP3mAsientoCab  implements java.io.Serializable {


     private EnP3mAsientoCabId id;
     private EnP3mLibroDiario enP3mLibroDiario;
     private TaGzzMoneda taGzzMoneda;
     private TaGzzTipoComprobante taGzzTipoComprobante;
     private char asiCabTip;
     private String asiCabGlo;
     private Date asiCabFec;
     private String asiCabNumCom;
     private char estRegCod;
     private Set enP3tAsientoDets = new HashSet(0);

    public EnP3mAsientoCab() {
    }

	
    public EnP3mAsientoCab(EnP3mAsientoCabId id, EnP3mLibroDiario enP3mLibroDiario, TaGzzMoneda taGzzMoneda, TaGzzTipoComprobante taGzzTipoComprobante, char asiCabTip, Date asiCabFec, char estRegCod) {
        this.id = id;
        this.enP3mLibroDiario = enP3mLibroDiario;
        this.taGzzMoneda = taGzzMoneda;
        this.taGzzTipoComprobante = taGzzTipoComprobante;
        this.asiCabTip = asiCabTip;
        this.asiCabFec = asiCabFec;
        this.estRegCod = estRegCod;
    }
    public EnP3mAsientoCab(EnP3mAsientoCabId id, EnP3mLibroDiario enP3mLibroDiario, TaGzzMoneda taGzzMoneda, TaGzzTipoComprobante taGzzTipoComprobante, char asiCabTip, String asiCabGlo, Date asiCabFec, String asiCabNumCom, char estRegCod, Set enP3tAsientoDets) {
       this.id = id;
       this.enP3mLibroDiario = enP3mLibroDiario;
       this.taGzzMoneda = taGzzMoneda;
       this.taGzzTipoComprobante = taGzzTipoComprobante;
       this.asiCabTip = asiCabTip;
       this.asiCabGlo = asiCabGlo;
       this.asiCabFec = asiCabFec;
       this.asiCabNumCom = asiCabNumCom;
       this.estRegCod = estRegCod;
       this.enP3tAsientoDets = enP3tAsientoDets;
    }
   
    public EnP3mAsientoCabId getId() {
        return this.id;
    }
    
    public void setId(EnP3mAsientoCabId id) {
        this.id = id;
    }
    public EnP3mLibroDiario getEnP3mLibroDiario() {
        return this.enP3mLibroDiario;
    }
    
    public void setEnP3mLibroDiario(EnP3mLibroDiario enP3mLibroDiario) {
        this.enP3mLibroDiario = enP3mLibroDiario;
    }
    public TaGzzMoneda getTaGzzMoneda() {
        return this.taGzzMoneda;
    }
    
    public void setTaGzzMoneda(TaGzzMoneda taGzzMoneda) {
        this.taGzzMoneda = taGzzMoneda;
    }
    public TaGzzTipoComprobante getTaGzzTipoComprobante() {
        return this.taGzzTipoComprobante;
    }
    
    public void setTaGzzTipoComprobante(TaGzzTipoComprobante taGzzTipoComprobante) {
        this.taGzzTipoComprobante = taGzzTipoComprobante;
    }
    public char getAsiCabTip() {
        return this.asiCabTip;
    }
    
    public void setAsiCabTip(char asiCabTip) {
        this.asiCabTip = asiCabTip;
    }
    public String getAsiCabGlo() {
        return this.asiCabGlo;
    }
    
    public void setAsiCabGlo(String asiCabGlo) {
        this.asiCabGlo = asiCabGlo;
    }
    public Date getAsiCabFec() {
        return this.asiCabFec;
    }
    
    public void setAsiCabFec(Date asiCabFec) {
        this.asiCabFec = asiCabFec;
    }
    public String getAsiCabNumCom() {
        return this.asiCabNumCom;
    }
    
    public void setAsiCabNumCom(String asiCabNumCom) {
        this.asiCabNumCom = asiCabNumCom;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP3tAsientoDets() {
        return this.enP3tAsientoDets;
    }
    
    public void setEnP3tAsientoDets(Set enP3tAsientoDets) {
        this.enP3tAsientoDets = enP3tAsientoDets;
    }




}


