package org.epis.minierp.model;
// Generated 28/10/2016 01:30:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnP3mCuenta generated by hbm2java
 */
public class EnP3mCuenta  implements java.io.Serializable, Comparable<EnP3mCuenta> {


     private Integer cueCod;
     private EnP3mCuenta enP3mCuenta;
     private int cueNiv;
     private String cueNum;
     private String cueDes;
     private char estRegCod;
     private Set enP3tAsientoDets = new HashSet(0);
     private Set enP3mCuentaBancos = new HashSet(0);
     private Set enP3mCuentas = new HashSet(0);
     private Set enP3tPlantillaDets = new HashSet(0);

    public EnP3mCuenta() {
    }

	
    public EnP3mCuenta(int cueNiv, String cueNum, String cueDes, char estRegCod) {
        this.cueNiv = cueNiv;
        this.cueNum = cueNum;
        this.cueDes = cueDes;
        this.estRegCod = estRegCod;
    }
    public EnP3mCuenta(EnP3mCuenta enP3mCuenta, int cueNiv, String cueNum, String cueDes, char estRegCod, Set enP3tAsientoDets, Set enP3mCuentaBancos, Set enP3mCuentas, Set enP3tPlantillaDets) {
       this.enP3mCuenta = enP3mCuenta;
       this.cueNiv = cueNiv;
       this.cueNum = cueNum;
       this.cueDes = cueDes;
       this.estRegCod = estRegCod;
       this.enP3tAsientoDets = enP3tAsientoDets;
       this.enP3mCuentaBancos = enP3mCuentaBancos;
       this.enP3mCuentas = enP3mCuentas;
       this.enP3tPlantillaDets = enP3tPlantillaDets;
    }
   
    public Integer getCueCod() {
        return this.cueCod;
    }
    
    public void setCueCod(Integer cueCod) {
        this.cueCod = cueCod;
    }
    public EnP3mCuenta getEnP3mCuenta() {
        return this.enP3mCuenta;
    }
    
    public void setEnP3mCuenta(EnP3mCuenta enP3mCuenta) {
        this.enP3mCuenta = enP3mCuenta;
    }
    public int getCueNiv() {
        return this.cueNiv;
    }
    
    public void setCueNiv(int cueNiv) {
        this.cueNiv = cueNiv;
    }
    public String getCueNum() {
        return this.cueNum;
    }
    
    public void setCueNum(String cueNum) {
        this.cueNum = cueNum;
    }
    public String getCueDes() {
        return this.cueDes;
    }
    
    public void setCueDes(String cueDes) {
        this.cueDes = cueDes;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP3tAsientoDets() {
        return this.enP3tAsientoDets;
    }
    
    public void setEnP3tAsientoDets(Set enP3tAsientoDets) {
        this.enP3tAsientoDets = enP3tAsientoDets;
    }
    public Set getEnP3mCuentaBancos() {
        return this.enP3mCuentaBancos;
    }
    
    public void setEnP3mCuentaBancos(Set enP3mCuentaBancos) {
        this.enP3mCuentaBancos = enP3mCuentaBancos;
    }
    public Set getEnP3mCuentas() {
        return this.enP3mCuentas;
    }
    
    public void setEnP3mCuentas(Set enP3mCuentas) {
        this.enP3mCuentas = enP3mCuentas;
    }
    public Set getEnP3tPlantillaDets() {
        return this.enP3tPlantillaDets;
    }
    
    public void setEnP3tPlantillaDets(Set enP3tPlantillaDets) {
        this.enP3tPlantillaDets = enP3tPlantillaDets;
    }
    
    @Override
    public int compareTo(EnP3mCuenta that){
        final int BEFORE = -1;
        final int AFTER = 1;
        if (that == null)
            return BEFORE;
        if(this.getCueNum().compareTo(that.getCueNum()) == 0)
            return AFTER;
        else
            return this.getCueNum().compareTo(that.getCueNum());
    }



}


