package org.epis.minierp.model;
// Generated 30/10/2016 12:40:40 AM by Hibernate Tools 4.3.1



/**
 * EnP3mCuentaBanco generated by hbm2java
 */
public class EnP3mCuentaBanco  implements java.io.Serializable {


     private Integer cueBanCod;
     private EnP3mCuenta enP3mCuenta;
     private TaGzzBanco taGzzBanco;
     private String cueBanNum;
     private char estRegCod;

    public EnP3mCuentaBanco() {
    }

    public EnP3mCuentaBanco(EnP3mCuenta enP3mCuenta, TaGzzBanco taGzzBanco, String cueBanNum, char estRegCod) {
       this.enP3mCuenta = enP3mCuenta;
       this.taGzzBanco = taGzzBanco;
       this.cueBanNum = cueBanNum;
       this.estRegCod = estRegCod;
    }
   
    public Integer getCueBanCod() {
        return this.cueBanCod;
    }
    
    public void setCueBanCod(Integer cueBanCod) {
        this.cueBanCod = cueBanCod;
    }
    public EnP3mCuenta getEnP3mCuenta() {
        return this.enP3mCuenta;
    }
    
    public void setEnP3mCuenta(EnP3mCuenta enP3mCuenta) {
        this.enP3mCuenta = enP3mCuenta;
    }
    public TaGzzBanco getTaGzzBanco() {
        return this.taGzzBanco;
    }
    
    public void setTaGzzBanco(TaGzzBanco taGzzBanco) {
        this.taGzzBanco = taGzzBanco;
    }
    public String getCueBanNum() {
        return this.cueBanNum;
    }
    
    public void setCueBanNum(String cueBanNum) {
        this.cueBanNum = cueBanNum;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


