package org.epis.minierp.model;
// Generated 28/10/2016 01:30:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EnP4mGuiaCompraCab generated by hbm2java
 */
public class EnP4mGuiaCompraCab  implements java.io.Serializable {


     private String guiComCabCod;
     private EnP4mFacturaCompraCab enP4mFacturaCompraCab;
     private EnP4mProveedor enP4mProveedor;
     private String guiComCabPunPar;
     private String guiComCabPunLle;
     private Date guiComCabFec;
     private char estRegCod;
     private Set enP4tGuiaCompraDets = new HashSet(0);

    public EnP4mGuiaCompraCab() {
    }

	
    public EnP4mGuiaCompraCab(String guiComCabCod, EnP4mFacturaCompraCab enP4mFacturaCompraCab, EnP4mProveedor enP4mProveedor, Date guiComCabFec, char estRegCod) {
        this.guiComCabCod = guiComCabCod;
        this.enP4mFacturaCompraCab = enP4mFacturaCompraCab;
        this.enP4mProveedor = enP4mProveedor;
        this.guiComCabFec = guiComCabFec;
        this.estRegCod = estRegCod;
    }
    public EnP4mGuiaCompraCab(String guiComCabCod, EnP4mFacturaCompraCab enP4mFacturaCompraCab, EnP4mProveedor enP4mProveedor, String guiComCabPunPar, String guiComCabPunLle, Date guiComCabFec, char estRegCod, Set enP4tGuiaCompraDets) {
       this.guiComCabCod = guiComCabCod;
       this.enP4mFacturaCompraCab = enP4mFacturaCompraCab;
       this.enP4mProveedor = enP4mProveedor;
       this.guiComCabPunPar = guiComCabPunPar;
       this.guiComCabPunLle = guiComCabPunLle;
       this.guiComCabFec = guiComCabFec;
       this.estRegCod = estRegCod;
       this.enP4tGuiaCompraDets = enP4tGuiaCompraDets;
    }
   
    public String getGuiComCabCod() {
        return this.guiComCabCod;
    }
    
    public void setGuiComCabCod(String guiComCabCod) {
        this.guiComCabCod = guiComCabCod;
    }
    public EnP4mFacturaCompraCab getEnP4mFacturaCompraCab() {
        return this.enP4mFacturaCompraCab;
    }
    
    public void setEnP4mFacturaCompraCab(EnP4mFacturaCompraCab enP4mFacturaCompraCab) {
        this.enP4mFacturaCompraCab = enP4mFacturaCompraCab;
    }
    public EnP4mProveedor getEnP4mProveedor() {
        return this.enP4mProveedor;
    }
    
    public void setEnP4mProveedor(EnP4mProveedor enP4mProveedor) {
        this.enP4mProveedor = enP4mProveedor;
    }
    public String getGuiComCabPunPar() {
        return this.guiComCabPunPar;
    }
    
    public void setGuiComCabPunPar(String guiComCabPunPar) {
        this.guiComCabPunPar = guiComCabPunPar;
    }
    public String getGuiComCabPunLle() {
        return this.guiComCabPunLle;
    }
    
    public void setGuiComCabPunLle(String guiComCabPunLle) {
        this.guiComCabPunLle = guiComCabPunLle;
    }
    public Date getGuiComCabFec() {
        return this.guiComCabFec;
    }
    
    public void setGuiComCabFec(Date guiComCabFec) {
        this.guiComCabFec = guiComCabFec;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP4tGuiaCompraDets() {
        return this.enP4tGuiaCompraDets;
    }
    
    public void setEnP4tGuiaCompraDets(Set enP4tGuiaCompraDets) {
        this.enP4tGuiaCompraDets = enP4tGuiaCompraDets;
    }




}


