package org.epis.minierp.model;
// Generated 25/11/2016 01:35:59 AM by Hibernate Tools 4.3.1



/**
 * EnP4mDocumentoProveedorId generated by hbm2java
 */
public class EnP4mDocumentoProveedorId  implements java.io.Serializable {


     private String prvCod;
     private int tipDocProCod;

    public EnP4mDocumentoProveedorId() {
    }

    public EnP4mDocumentoProveedorId(String prvCod, int tipDocProCod) {
       this.prvCod = prvCod;
       this.tipDocProCod = tipDocProCod;
    }
   
    public String getPrvCod() {
        return this.prvCod;
    }
    
    public void setPrvCod(String prvCod) {
        this.prvCod = prvCod;
    }
    public int getTipDocProCod() {
        return this.tipDocProCod;
    }
    
    public void setTipDocProCod(int tipDocProCod) {
        this.tipDocProCod = tipDocProCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnP4mDocumentoProveedorId) ) return false;
		 EnP4mDocumentoProveedorId castOther = ( EnP4mDocumentoProveedorId ) other; 
         
		 return ( (this.getPrvCod()==castOther.getPrvCod()) || ( this.getPrvCod()!=null && castOther.getPrvCod()!=null && this.getPrvCod().equals(castOther.getPrvCod()) ) )
 && (this.getTipDocProCod()==castOther.getTipDocProCod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPrvCod() == null ? 0 : this.getPrvCod().hashCode() );
         result = 37 * result + this.getTipDocProCod();
         return result;
   }   


}


