package org.epis.minierp.model;
// Generated 28/10/2016 01:30:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EnP4mFacturaCompraCab generated by hbm2java
 */
public class EnP4mFacturaCompraCab  implements java.io.Serializable {


     private String facComCabCod;
     private EnP1mUsuario enP1mUsuario;
     private EnP4mProveedor enP4mProveedor;
     private TaGzzEstadoFactura taGzzEstadoFactura;
     private TaGzzMetodoPagoFactura taGzzMetodoPagoFactura;
     private TaGzzMoneda taGzzMoneda;
     private TaGzzTipoPagoFactura taGzzTipoPagoFactura;
     private Date facComCabFec;
     private double facComCabTot;
     private double facComCabDes;
     private double facComCabSubTot;
     private int facComCabIgv;
     private String facComCabObs;
     private char estRegCod;
     private Set enP4mGuiaCompraCabs = new HashSet(0);
     private Set enP4tFacturaCompraDets = new HashSet(0);

    public EnP4mFacturaCompraCab() {
    }

	
    public EnP4mFacturaCompraCab(String facComCabCod, EnP1mUsuario enP1mUsuario, EnP4mProveedor enP4mProveedor, TaGzzEstadoFactura taGzzEstadoFactura, TaGzzMetodoPagoFactura taGzzMetodoPagoFactura, TaGzzMoneda taGzzMoneda, TaGzzTipoPagoFactura taGzzTipoPagoFactura, Date facComCabFec, double facComCabTot, double facComCabDes, double facComCabSubTot, int facComCabIgv, String facComCabObs, char estRegCod) {
        this.facComCabCod = facComCabCod;
        this.enP1mUsuario = enP1mUsuario;
        this.enP4mProveedor = enP4mProveedor;
        this.taGzzEstadoFactura = taGzzEstadoFactura;
        this.taGzzMetodoPagoFactura = taGzzMetodoPagoFactura;
        this.taGzzMoneda = taGzzMoneda;
        this.taGzzTipoPagoFactura = taGzzTipoPagoFactura;
        this.facComCabFec = facComCabFec;
        this.facComCabTot = facComCabTot;
        this.facComCabDes = facComCabDes;
        this.facComCabSubTot = facComCabSubTot;
        this.facComCabIgv = facComCabIgv;
        this.facComCabObs = facComCabObs;
        this.estRegCod = estRegCod;
    }
    public EnP4mFacturaCompraCab(String facComCabCod, EnP1mUsuario enP1mUsuario, EnP4mProveedor enP4mProveedor, TaGzzEstadoFactura taGzzEstadoFactura, TaGzzMetodoPagoFactura taGzzMetodoPagoFactura, TaGzzMoneda taGzzMoneda, TaGzzTipoPagoFactura taGzzTipoPagoFactura, Date facComCabFec, double facComCabTot, double facComCabDes, double facComCabSubTot, int facComCabIgv, String facComCabObs, char estRegCod, Set enP4mGuiaCompraCabs, Set enP4tFacturaCompraDets) {
       this.facComCabCod = facComCabCod;
       this.enP1mUsuario = enP1mUsuario;
       this.enP4mProveedor = enP4mProveedor;
       this.taGzzEstadoFactura = taGzzEstadoFactura;
       this.taGzzMetodoPagoFactura = taGzzMetodoPagoFactura;
       this.taGzzMoneda = taGzzMoneda;
       this.taGzzTipoPagoFactura = taGzzTipoPagoFactura;
       this.facComCabFec = facComCabFec;
       this.facComCabTot = facComCabTot;
       this.facComCabDes = facComCabDes;
       this.facComCabSubTot = facComCabSubTot;
       this.facComCabIgv = facComCabIgv;
       this.facComCabObs = facComCabObs;
       this.estRegCod = estRegCod;
       this.enP4mGuiaCompraCabs = enP4mGuiaCompraCabs;
       this.enP4tFacturaCompraDets = enP4tFacturaCompraDets;
    }
   
    public String getFacComCabCod() {
        return this.facComCabCod;
    }
    
    public void setFacComCabCod(String facComCabCod) {
        this.facComCabCod = facComCabCod;
    }
    public EnP1mUsuario getEnP1mUsuario() {
        return this.enP1mUsuario;
    }
    
    public void setEnP1mUsuario(EnP1mUsuario enP1mUsuario) {
        this.enP1mUsuario = enP1mUsuario;
    }
    public EnP4mProveedor getEnP4mProveedor() {
        return this.enP4mProveedor;
    }
    
    public void setEnP4mProveedor(EnP4mProveedor enP4mProveedor) {
        this.enP4mProveedor = enP4mProveedor;
    }
    public TaGzzEstadoFactura getTaGzzEstadoFactura() {
        return this.taGzzEstadoFactura;
    }
    
    public void setTaGzzEstadoFactura(TaGzzEstadoFactura taGzzEstadoFactura) {
        this.taGzzEstadoFactura = taGzzEstadoFactura;
    }
    public TaGzzMetodoPagoFactura getTaGzzMetodoPagoFactura() {
        return this.taGzzMetodoPagoFactura;
    }
    
    public void setTaGzzMetodoPagoFactura(TaGzzMetodoPagoFactura taGzzMetodoPagoFactura) {
        this.taGzzMetodoPagoFactura = taGzzMetodoPagoFactura;
    }
    public TaGzzMoneda getTaGzzMoneda() {
        return this.taGzzMoneda;
    }
    
    public void setTaGzzMoneda(TaGzzMoneda taGzzMoneda) {
        this.taGzzMoneda = taGzzMoneda;
    }
    public TaGzzTipoPagoFactura getTaGzzTipoPagoFactura() {
        return this.taGzzTipoPagoFactura;
    }
    
    public void setTaGzzTipoPagoFactura(TaGzzTipoPagoFactura taGzzTipoPagoFactura) {
        this.taGzzTipoPagoFactura = taGzzTipoPagoFactura;
    }
    public Date getFacComCabFec() {
        return this.facComCabFec;
    }
    
    public void setFacComCabFec(Date facComCabFec) {
        this.facComCabFec = facComCabFec;
    }
    public double getFacComCabTot() {
        return this.facComCabTot;
    }
    
    public void setFacComCabTot(double facComCabTot) {
        this.facComCabTot = facComCabTot;
    }
    public double getFacComCabDes() {
        return this.facComCabDes;
    }
    
    public void setFacComCabDes(double facComCabDes) {
        this.facComCabDes = facComCabDes;
    }
    public double getFacComCabSubTot() {
        return this.facComCabSubTot;
    }
    
    public void setFacComCabSubTot(double facComCabSubTot) {
        this.facComCabSubTot = facComCabSubTot;
    }
    public int getFacComCabIgv() {
        return this.facComCabIgv;
    }
    
    public void setFacComCabIgv(int facComCabIgv) {
        this.facComCabIgv = facComCabIgv;
    }
    public String getFacComCabObs() {
        return this.facComCabObs;
    }
    
    public void setFacComCabObs(String facComCabObs) {
        this.facComCabObs = facComCabObs;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP4mGuiaCompraCabs() {
        return this.enP4mGuiaCompraCabs;
    }
    
    public void setEnP4mGuiaCompraCabs(Set enP4mGuiaCompraCabs) {
        this.enP4mGuiaCompraCabs = enP4mGuiaCompraCabs;
    }
    public Set getEnP4tFacturaCompraDets() {
        return this.enP4tFacturaCompraDets;
    }
    
    public void setEnP4tFacturaCompraDets(Set enP4tFacturaCompraDets) {
        this.enP4tFacturaCompraDets = enP4tFacturaCompraDets;
    }




}


