package org.epis.minierp.model;
// Generated 07/10/2016 11:13:21 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoCivil generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_estado_civil"
)
public class EstadoCivil  implements java.io.Serializable {


     private int estCivCod;
     private String estCivDet;
     private char estRegCod;

    public EstadoCivil() {
    }

	
    public EstadoCivil(int estCivCod) {
        this.estCivCod = estCivCod;
    }
    public EstadoCivil(int estCivCod, String estCivDet, char estRegCod) {
       this.estCivCod = estCivCod;
       this.estCivDet = estCivDet;
       this.estRegCod = estRegCod;
    }
   
     @Id 

    
    @Column(name="estCivCod", nullable=false)
    public int getEstCivCod() {
        return this.estCivCod;
    }
    
    public void setEstCivCod(int estCivCod) {
        this.estCivCod = estCivCod;
    }

    
    @Column(name="EstCivDet")
    public String getEstCivDet() {
        return this.estCivDet;
    }
    
    public void setEstCivDet(String estCivDet) {
        this.estCivDet = estCivDet;
    }

    
    @Column(name="EstRegCod")
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


