package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaGzzTipoUniTransporte generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_tipo_uni_transporte"
    ,catalog="episerp"
)
public class TaGzzTipoUniTransporte  implements java.io.Serializable {


     private Integer tipUniTraCod;
     private String tipUniTraDet;
     private Character estRegCod;
     private Set enP2mUnidadTransportes = new HashSet(0);

    public TaGzzTipoUniTransporte() {
    }

	
    public TaGzzTipoUniTransporte(String tipUniTraDet) {
        this.tipUniTraDet = tipUniTraDet;
    }
    public TaGzzTipoUniTransporte(String tipUniTraDet, Character estRegCod, Set enP2mUnidadTransportes) {
       this.tipUniTraDet = tipUniTraDet;
       this.estRegCod = estRegCod;
       this.enP2mUnidadTransportes = enP2mUnidadTransportes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TipUniTraCod", unique=true, nullable=false)
    public Integer getTipUniTraCod() {
        return this.tipUniTraCod;
    }
    
    public void setTipUniTraCod(Integer tipUniTraCod) {
        this.tipUniTraCod = tipUniTraCod;
    }

    
    @Column(name="TipUniTraDet", nullable=false, length=90)
    public String getTipUniTraDet() {
        return this.tipUniTraDet;
    }
    
    public void setTipUniTraDet(String tipUniTraDet) {
        this.tipUniTraDet = tipUniTraDet;
    }

    
    @Column(name="EstRegCod", length=1)
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzTipoUniTransporte")
    public Set getEnP2mUnidadTransportes() {
        return this.enP2mUnidadTransportes;
    }
    
    public void setEnP2mUnidadTransportes(Set enP2mUnidadTransportes) {
        this.enP2mUnidadTransportes = enP2mUnidadTransportes;
    }




}


