package org.epis.minierp.model;
// Generated 29/10/2016 12:36:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaGzzTipoFacturaBoleta generated by hbm2java
 */
public class TaGzzTipoFacturaBoleta  implements java.io.Serializable {


     private Integer tipFacObolCod;
     private String tipFacObolDet;
     private Character estRegCod;
     private Set enP1mFacturaVentaCabs = new HashSet(0);
     private Set enP4mFacturaCompraCabs = new HashSet(0);

    public TaGzzTipoFacturaBoleta() {
    }

	
    public TaGzzTipoFacturaBoleta(String tipFacObolDet) {
        this.tipFacObolDet = tipFacObolDet;
    }
    public TaGzzTipoFacturaBoleta(String tipFacObolDet, Character estRegCod, Set enP1mFacturaVentaCabs, Set enP4mFacturaCompraCabs) {
       this.tipFacObolDet = tipFacObolDet;
       this.estRegCod = estRegCod;
       this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
       this.enP4mFacturaCompraCabs = enP4mFacturaCompraCabs;
    }
   
    public Integer getTipFacObolCod() {
        return this.tipFacObolCod;
    }
    
    public void setTipFacObolCod(Integer tipFacObolCod) {
        this.tipFacObolCod = tipFacObolCod;
    }
    public String getTipFacObolDet() {
        return this.tipFacObolDet;
    }
    
    public void setTipFacObolDet(String tipFacObolDet) {
        this.tipFacObolDet = tipFacObolDet;
    }
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP1mFacturaVentaCabs() {
        return this.enP1mFacturaVentaCabs;
    }
    
    public void setEnP1mFacturaVentaCabs(Set enP1mFacturaVentaCabs) {
        this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
    }
    public Set getEnP4mFacturaCompraCabs() {
        return this.enP4mFacturaCompraCabs;
    }
    
    public void setEnP4mFacturaCompraCabs(Set enP4mFacturaCompraCabs) {
        this.enP4mFacturaCompraCabs = enP4mFacturaCompraCabs;
    }




}


