package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaGzzTipoDevolucion generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_tipo_devolucion"
    ,catalog="episerp"
)
public class TaGzzTipoDevolucion  implements java.io.Serializable {


     private Integer tipDevCod;
     private String tipDevDet;
     private Character estRegCod;
     private Set enP2cDevolucionComprases = new HashSet(0);
     private Set enP1cDevolucionVentases = new HashSet(0);

    public TaGzzTipoDevolucion() {
    }

	
    public TaGzzTipoDevolucion(String tipDevDet) {
        this.tipDevDet = tipDevDet;
    }
    public TaGzzTipoDevolucion(String tipDevDet, Character estRegCod, Set enP2cDevolucionComprases, Set enP1cDevolucionVentases) {
       this.tipDevDet = tipDevDet;
       this.estRegCod = estRegCod;
       this.enP2cDevolucionComprases = enP2cDevolucionComprases;
       this.enP1cDevolucionVentases = enP1cDevolucionVentases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TipDevCod", unique=true, nullable=false)
    public Integer getTipDevCod() {
        return this.tipDevCod;
    }
    
    public void setTipDevCod(Integer tipDevCod) {
        this.tipDevCod = tipDevCod;
    }

    
    @Column(name="TipDevDet", nullable=false, length=90)
    public String getTipDevDet() {
        return this.tipDevDet;
    }
    
    public void setTipDevDet(String tipDevDet) {
        this.tipDevDet = tipDevDet;
    }

    
    @Column(name="EstRegCod", length=1)
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzTipoDevolucion")
    public Set getEnP2cDevolucionComprases() {
        return this.enP2cDevolucionComprases;
    }
    
    public void setEnP2cDevolucionComprases(Set enP2cDevolucionComprases) {
        this.enP2cDevolucionComprases = enP2cDevolucionComprases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzTipoDevolucion")
    public Set getEnP1cDevolucionVentases() {
        return this.enP1cDevolucionVentases;
    }
    
    public void setEnP1cDevolucionVentases(Set enP1cDevolucionVentases) {
        this.enP1cDevolucionVentases = enP1cDevolucionVentases;
    }




}


