package org.epis.minierp.model;
// Generated 07/10/2016 09:29:17 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaGzzBanco generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_banco"
    ,catalog="episerp"
)
public class TaGzzBanco  implements java.io.Serializable {


     private Integer banCod;
     private String banDet;
     private char estRegCod;

    public TaGzzBanco() {
    }

    public TaGzzBanco(String banDet, char estRegCod) {
       this.banDet = banDet;
       this.estRegCod = estRegCod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BanCod", unique=true, nullable=false)
    public Integer getBanCod() {
        return this.banCod;
    }
    
    public void setBanCod(Integer banCod) {
        this.banCod = banCod;
    }

    
    @Column(name="BanDet", nullable=false, length=90)
    public String getBanDet() {
        return this.banDet;
    }
    
    public void setBanDet(String banDet) {
        this.banDet = banDet;
    }

    
    @Column(name="EstRegCod", nullable=false, length=1)
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


