package org.epis.minierp.model;
// Generated 30/10/2016 12:40:40 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaGzzTipoPagoFactura generated by hbm2java
 */
public class TaGzzTipoPagoFactura  implements java.io.Serializable {


     private Integer tipPagCod;
     private String tipPagDet;
     private char estRegCod;
     private Set enP4mFacturaCompraCabs = new HashSet(0);
     private Set enP1mFacturaVentaCabs = new HashSet(0);

    public TaGzzTipoPagoFactura() {
    }

	
    public TaGzzTipoPagoFactura(String tipPagDet, char estRegCod) {
        this.tipPagDet = tipPagDet;
        this.estRegCod = estRegCod;
    }
    public TaGzzTipoPagoFactura(String tipPagDet, char estRegCod, Set enP4mFacturaCompraCabs, Set enP1mFacturaVentaCabs) {
       this.tipPagDet = tipPagDet;
       this.estRegCod = estRegCod;
       this.enP4mFacturaCompraCabs = enP4mFacturaCompraCabs;
       this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
    }
   
    public Integer getTipPagCod() {
        return this.tipPagCod;
    }
    
    public void setTipPagCod(Integer tipPagCod) {
        this.tipPagCod = tipPagCod;
    }
    public String getTipPagDet() {
        return this.tipPagDet;
    }
    
    public void setTipPagDet(String tipPagDet) {
        this.tipPagDet = tipPagDet;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP4mFacturaCompraCabs() {
        return this.enP4mFacturaCompraCabs;
    }
    
    public void setEnP4mFacturaCompraCabs(Set enP4mFacturaCompraCabs) {
        this.enP4mFacturaCompraCabs = enP4mFacturaCompraCabs;
    }
    public Set getEnP1mFacturaVentaCabs() {
        return this.enP1mFacturaVentaCabs;
    }
    
    public void setEnP1mFacturaVentaCabs(Set enP1mFacturaVentaCabs) {
        this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
    }




}


