package org.epis.minierp.model;
// Generated 05/11/2016 03:48:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaGzzTipoDocTransportista generated by hbm2java
 */
public class TaGzzTipoDocTransportista  implements java.io.Serializable {


     private Integer tipDocTraCod;
     private String tipDocTraDet;
     private Character estRegCod;
     private Set enP2mDocumentoTransportistas = new HashSet(0);

    public TaGzzTipoDocTransportista() {
    }

	
    public TaGzzTipoDocTransportista(String tipDocTraDet) {
        this.tipDocTraDet = tipDocTraDet;
    }
    public TaGzzTipoDocTransportista(String tipDocTraDet, Character estRegCod, Set enP2mDocumentoTransportistas) {
       this.tipDocTraDet = tipDocTraDet;
       this.estRegCod = estRegCod;
       this.enP2mDocumentoTransportistas = enP2mDocumentoTransportistas;
    }
   
    public Integer getTipDocTraCod() {
        return this.tipDocTraCod;
    }
    
    public void setTipDocTraCod(Integer tipDocTraCod) {
        this.tipDocTraCod = tipDocTraCod;
    }
    public String getTipDocTraDet() {
        return this.tipDocTraDet;
    }
    
    public void setTipDocTraDet(String tipDocTraDet) {
        this.tipDocTraDet = tipDocTraDet;
    }
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP2mDocumentoTransportistas() {
        return this.enP2mDocumentoTransportistas;
    }
    
    public void setEnP2mDocumentoTransportistas(Set enP2mDocumentoTransportistas) {
        this.enP2mDocumentoTransportistas = enP2mDocumentoTransportistas;
    }




}


