package org.epis.minierp.model;
// Generated 09/11/2016 04:17:17 PM by Hibernate Tools 4.3.1



/**
 * TaGzzTipoFallaProducto generated by hbm2java
 */
public class TaGzzTipoFallaProducto  implements java.io.Serializable {


     private Integer tipFallProCod;
     private String tipFallProDet;
     private char estRegCod;

    public TaGzzTipoFallaProducto() {
    }

    public TaGzzTipoFallaProducto(String tipFallProDet, char estRegCod) {
       this.tipFallProDet = tipFallProDet;
       this.estRegCod = estRegCod;
    }
   
    public Integer getTipFallProCod() {
        return this.tipFallProCod;
    }
    
    public void setTipFallProCod(Integer tipFallProCod) {
        this.tipFallProCod = tipFallProCod;
    }
    public String getTipFallProDet() {
        return this.tipFallProDet;
    }
    
    public void setTipFallProDet(String tipFallProDet) {
        this.tipFallProDet = tipFallProDet;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }




}


