package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaGzzMotivoTraslado generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_motivo_traslado"
    ,catalog="episerp"
)
public class TaGzzMotivoTraslado  implements java.io.Serializable {


     private Integer motTraCod;
     private String motTraDet;
     private Character estRegCod;
     private Set enP2mGuiaRemRemitentes = new HashSet(0);

    public TaGzzMotivoTraslado() {
    }

	
    public TaGzzMotivoTraslado(String motTraDet) {
        this.motTraDet = motTraDet;
    }
    public TaGzzMotivoTraslado(String motTraDet, Character estRegCod, Set enP2mGuiaRemRemitentes) {
       this.motTraDet = motTraDet;
       this.estRegCod = estRegCod;
       this.enP2mGuiaRemRemitentes = enP2mGuiaRemRemitentes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MotTraCod", unique=true, nullable=false)
    public Integer getMotTraCod() {
        return this.motTraCod;
    }
    
    public void setMotTraCod(Integer motTraCod) {
        this.motTraCod = motTraCod;
    }

    
    @Column(name="MotTraDet", nullable=false, length=90)
    public String getMotTraDet() {
        return this.motTraDet;
    }
    
    public void setMotTraDet(String motTraDet) {
        this.motTraDet = motTraDet;
    }

    
    @Column(name="EstRegCod", length=1)
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzMotivoTraslado")
    public Set getEnP2mGuiaRemRemitentes() {
        return this.enP2mGuiaRemRemitentes;
    }
    
    public void setEnP2mGuiaRemRemitentes(Set enP2mGuiaRemRemitentes) {
        this.enP2mGuiaRemRemitentes = enP2mGuiaRemRemitentes;
    }




}


