package org.epis.minierp.model;
// Generated 05/11/2016 04:10:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaGzzTipoDescuento generated by hbm2java
 */
public class TaGzzTipoDescuento  implements java.io.Serializable {


     private Integer tipDesCod;
     private String tipDesDet;
     private Character estRegCod;
     private Set enP1mPreventaCabs = new HashSet(0);
     private Set enP1mFacturaVentaCabs = new HashSet(0);
     private Set enP4mFacturaCompraCabs = new HashSet(0);

    public TaGzzTipoDescuento() {
    }

	
    public TaGzzTipoDescuento(String tipDesDet) {
        this.tipDesDet = tipDesDet;
    }
    public TaGzzTipoDescuento(String tipDesDet, Character estRegCod, Set enP1mPreventaCabs, Set enP1mFacturaVentaCabs, Set enP4mFacturaCompraCabs) {
       this.tipDesDet = tipDesDet;
       this.estRegCod = estRegCod;
       this.enP1mPreventaCabs = enP1mPreventaCabs;
       this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
       this.enP4mFacturaCompraCabs = enP4mFacturaCompraCabs;
    }
   
    public Integer getTipDesCod() {
        return this.tipDesCod;
    }
    
    public void setTipDesCod(Integer tipDesCod) {
        this.tipDesCod = tipDesCod;
    }
    public String getTipDesDet() {
        return this.tipDesDet;
    }
    
    public void setTipDesDet(String tipDesDet) {
        this.tipDesDet = tipDesDet;
    }
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP1mPreventaCabs() {
        return this.enP1mPreventaCabs;
    }
    
    public void setEnP1mPreventaCabs(Set enP1mPreventaCabs) {
        this.enP1mPreventaCabs = enP1mPreventaCabs;
    }
    public Set getEnP1mFacturaVentaCabs() {
        return this.enP1mFacturaVentaCabs;
    }
    
    public void setEnP1mFacturaVentaCabs(Set enP1mFacturaVentaCabs) {
        this.enP1mFacturaVentaCabs = enP1mFacturaVentaCabs;
    }
    public Set getEnP4mFacturaCompraCabs() {
        return this.enP4mFacturaCompraCabs;
    }
    
    public void setEnP4mFacturaCompraCabs(Set enP4mFacturaCompraCabs) {
        this.enP4mFacturaCompraCabs = enP4mFacturaCompraCabs;
    }




}


