package org.epis.minierp.model;
// Generated 26/02/2017 07:56:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaGzzCanalUsuario generated by hbm2java
 */
public class TaGzzCanalUsuario  implements java.io.Serializable {


     private int canUsuCod;
     private String canUsuDet;
     private Double canUsuPorAdd;
     private char estRegCod;
     private Set enP1mUsuarios = new HashSet(0);

    public TaGzzCanalUsuario() {
    }

	
    public TaGzzCanalUsuario(int canUsuCod, String canUsuDet, char estRegCod) {
        this.canUsuCod = canUsuCod;
        this.canUsuDet = canUsuDet;
        this.estRegCod = estRegCod;
    }
    public TaGzzCanalUsuario(int canUsuCod, String canUsuDet, Double canUsuPorAdd, char estRegCod, Set enP1mUsuarios) {
       this.canUsuCod = canUsuCod;
       this.canUsuDet = canUsuDet;
       this.canUsuPorAdd = canUsuPorAdd;
       this.estRegCod = estRegCod;
       this.enP1mUsuarios = enP1mUsuarios;
    }
   
    public int getCanUsuCod() {
        return this.canUsuCod;
    }
    
    public void setCanUsuCod(int canUsuCod) {
        this.canUsuCod = canUsuCod;
    }
    public String getCanUsuDet() {
        return this.canUsuDet;
    }
    
    public void setCanUsuDet(String canUsuDet) {
        this.canUsuDet = canUsuDet;
    }
    public Double getCanUsuPorAdd() {
        return this.canUsuPorAdd;
    }
    
    public void setCanUsuPorAdd(Double canUsuPorAdd) {
        this.canUsuPorAdd = canUsuPorAdd;
    }
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP1mUsuarios() {
        return this.enP1mUsuarios;
    }
    
    public void setEnP1mUsuarios(Set enP1mUsuarios) {
        this.enP1mUsuarios = enP1mUsuarios;
    }




}


