package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaGzzTipoDocTransportista generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_tipo_doc_transportista"
    ,catalog="episerp"
)
public class TaGzzTipoDocTransportista  implements java.io.Serializable {


     private Integer tipDocTraCod;
     private String tipDocTraDet;
     private Character estRegCod;
     private Set enP2mDocumentoTransportistas = new HashSet(0);

    public TaGzzTipoDocTransportista() {
    }

	
    public TaGzzTipoDocTransportista(String tipDocTraDet) {
        this.tipDocTraDet = tipDocTraDet;
    }
    public TaGzzTipoDocTransportista(String tipDocTraDet, Character estRegCod, Set enP2mDocumentoTransportistas) {
       this.tipDocTraDet = tipDocTraDet;
       this.estRegCod = estRegCod;
       this.enP2mDocumentoTransportistas = enP2mDocumentoTransportistas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TipDocTraCod", unique=true, nullable=false)
    public Integer getTipDocTraCod() {
        return this.tipDocTraCod;
    }
    
    public void setTipDocTraCod(Integer tipDocTraCod) {
        this.tipDocTraCod = tipDocTraCod;
    }

    
    @Column(name="TipDocTraDet", nullable=false, length=90)
    public String getTipDocTraDet() {
        return this.tipDocTraDet;
    }
    
    public void setTipDocTraDet(String tipDocTraDet) {
        this.tipDocTraDet = tipDocTraDet;
    }

    
    @Column(name="EstRegCod", length=1)
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzTipoDocTransportista")
    public Set getEnP2mDocumentoTransportistas() {
        return this.enP2mDocumentoTransportistas;
    }
    
    public void setEnP2mDocumentoTransportistas(Set enP2mDocumentoTransportistas) {
        this.enP2mDocumentoTransportistas = enP2mDocumentoTransportistas;
    }




}


