package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaGzzTipoCliente generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_tipo_cliente"
    ,catalog="episerp"
)
public class TaGzzTipoCliente  implements java.io.Serializable {


     private Integer tipCliCod;
     private String tipCliDet;
     private Character estRegCod;
     private Set enP1mClientes = new HashSet(0);

    public TaGzzTipoCliente() {
    }

	
    public TaGzzTipoCliente(String tipCliDet) {
        this.tipCliDet = tipCliDet;
    }
    public TaGzzTipoCliente(String tipCliDet, Character estRegCod, Set enP1mClientes) {
       this.tipCliDet = tipCliDet;
       this.estRegCod = estRegCod;
       this.enP1mClientes = enP1mClientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TipCliCod", unique=true, nullable=false)
    public Integer getTipCliCod() {
        return this.tipCliCod;
    }
    
    public void setTipCliCod(Integer tipCliCod) {
        this.tipCliCod = tipCliCod;
    }

    
    @Column(name="TipCliDet", nullable=false, length=90)
    public String getTipCliDet() {
        return this.tipCliDet;
    }
    
    public void setTipCliDet(String tipCliDet) {
        this.tipCliDet = tipCliDet;
    }

    
    @Column(name="EstRegCod", length=1)
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzTipoCliente")
    public Set getEnP1mClientes() {
        return this.enP1mClientes;
    }
    
    public void setEnP1mClientes(Set enP1mClientes) {
        this.enP1mClientes = enP1mClientes;
    }




}


