package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaGzzEstadoUniTransporte generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_estado_uni_transporte"
    ,catalog="episerp"
)
public class TaGzzEstadoUniTransporte  implements java.io.Serializable {


     private Integer estUniTraCod;
     private String estUniTraDet;
     private Character estRegCod;
     private Set enP2mUnidadTransportes = new HashSet(0);

    public TaGzzEstadoUniTransporte() {
    }

	
    public TaGzzEstadoUniTransporte(String estUniTraDet) {
        this.estUniTraDet = estUniTraDet;
    }
    public TaGzzEstadoUniTransporte(String estUniTraDet, Character estRegCod, Set enP2mUnidadTransportes) {
       this.estUniTraDet = estUniTraDet;
       this.estRegCod = estRegCod;
       this.enP2mUnidadTransportes = enP2mUnidadTransportes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EstUniTraCod", unique=true, nullable=false)
    public Integer getEstUniTraCod() {
        return this.estUniTraCod;
    }
    
    public void setEstUniTraCod(Integer estUniTraCod) {
        this.estUniTraCod = estUniTraCod;
    }

    
    @Column(name="EstUniTraDet", nullable=false, length=90)
    public String getEstUniTraDet() {
        return this.estUniTraDet;
    }
    
    public void setEstUniTraDet(String estUniTraDet) {
        this.estUniTraDet = estUniTraDet;
    }

    
    @Column(name="EstRegCod", length=1)
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzEstadoUniTransporte")
    public Set getEnP2mUnidadTransportes() {
        return this.enP2mUnidadTransportes;
    }
    
    public void setEnP2mUnidadTransportes(Set enP2mUnidadTransportes) {
        this.enP2mUnidadTransportes = enP2mUnidadTransportes;
    }




}


