package org.epis.minierp.model;
// Generated 04/03/2017 10:43:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TaGzzUnidadTrabajo generated by hbm2java
 */
public class TaGzzUnidadTrabajo  implements java.io.Serializable {


     private int uniTraCod;
     private String uniTraDet;
     private Character estRegCod;
     private Set enP1mUsuarios = new HashSet(0);

    public TaGzzUnidadTrabajo() {
    }

	
    public TaGzzUnidadTrabajo(int uniTraCod) {
        this.uniTraCod = uniTraCod;
    }
    public TaGzzUnidadTrabajo(int uniTraCod, String uniTraDet, Character estRegCod, Set enP1mUsuarios) {
       this.uniTraCod = uniTraCod;
       this.uniTraDet = uniTraDet;
       this.estRegCod = estRegCod;
       this.enP1mUsuarios = enP1mUsuarios;
    }
   
    public int getUniTraCod() {
        return this.uniTraCod;
    }
    
    public void setUniTraCod(int uniTraCod) {
        this.uniTraCod = uniTraCod;
    }
    public String getUniTraDet() {
        return this.uniTraDet;
    }
    
    public void setUniTraDet(String uniTraDet) {
        this.uniTraDet = uniTraDet;
    }
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }
    public Set getEnP1mUsuarios() {
        return this.enP1mUsuarios;
    }
    
    public void setEnP1mUsuarios(Set enP1mUsuarios) {
        this.enP1mUsuarios = enP1mUsuarios;
    }




}


