package org.epis.minierp.model;
// Generated 28/10/2016 10:46:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaGzzTipoDestinatario generated by hbm2java
 */
@Entity
@Table(name="ta_gzz_tipo_destinatario"
    ,catalog="episerp"
)
public class TaGzzTipoDestinatario  implements java.io.Serializable {


     private Integer tipDesCod;
     private String tipDesDet;
     private Character estRegCod;
     private Set enP2mGuiaRemRemitentes = new HashSet(0);
     private Set enP2mGuiaRemTransportistas = new HashSet(0);

    public TaGzzTipoDestinatario() {
    }

	
    public TaGzzTipoDestinatario(String tipDesDet) {
        this.tipDesDet = tipDesDet;
    }
    public TaGzzTipoDestinatario(String tipDesDet, Character estRegCod, Set enP2mGuiaRemRemitentes, Set enP2mGuiaRemTransportistas) {
       this.tipDesDet = tipDesDet;
       this.estRegCod = estRegCod;
       this.enP2mGuiaRemRemitentes = enP2mGuiaRemRemitentes;
       this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TipDesCod", unique=true, nullable=false)
    public Integer getTipDesCod() {
        return this.tipDesCod;
    }
    
    public void setTipDesCod(Integer tipDesCod) {
        this.tipDesCod = tipDesCod;
    }

    
    @Column(name="TipDesDet", nullable=false, length=90)
    public String getTipDesDet() {
        return this.tipDesDet;
    }
    
    public void setTipDesDet(String tipDesDet) {
        this.tipDesDet = tipDesDet;
    }

    
    @Column(name="EstRegCod", length=1)
    public Character getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(Character estRegCod) {
        this.estRegCod = estRegCod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzTipoDestinatario")
    public Set getEnP2mGuiaRemRemitentes() {
        return this.enP2mGuiaRemRemitentes;
    }
    
    public void setEnP2mGuiaRemRemitentes(Set enP2mGuiaRemRemitentes) {
        this.enP2mGuiaRemRemitentes = enP2mGuiaRemRemitentes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taGzzTipoDestinatario")
    public Set getEnP2mGuiaRemTransportistas() {
        return this.enP2mGuiaRemTransportistas;
    }
    
    public void setEnP2mGuiaRemTransportistas(Set enP2mGuiaRemTransportistas) {
        this.enP2mGuiaRemTransportistas = enP2mGuiaRemTransportistas;
    }




}


