package org.epis.minierp.model;
// Generated 07/10/2016 11:13:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="en_p1m_usuario"
)
public class Usuario  implements java.io.Serializable {


     private String usuCod;
     private int estCivCod;
     private char estRegCod;
     private int tipUsuCod;
     private String usuApeMat;
     private String usuApePat;
     private Date usuFecNac;
     private byte[] usuHue;
     private String usuLog;
     private String usuNom;
     private String usuPas;
     private char usuSex;

    public Usuario() {
    }

	
    public Usuario(String usuCod) {
        this.usuCod = usuCod;
    }
    public Usuario(String usuCod, int estCivCod, char estRegCod, int tipUsuCod, String usuApeMat, String usuApePat, Date usuFecNac, byte[] usuHue, String usuLog, String usuNom, String usuPas, char usuSex) {
       this.usuCod = usuCod;
       this.estCivCod = estCivCod;
       this.estRegCod = estRegCod;
       this.tipUsuCod = tipUsuCod;
       this.usuApeMat = usuApeMat;
       this.usuApePat = usuApePat;
       this.usuFecNac = usuFecNac;
       this.usuHue = usuHue;
       this.usuLog = usuLog;
       this.usuNom = usuNom;
       this.usuPas = usuPas;
       this.usuSex = usuSex;
    }
   
     @Id 

    
    @Column(name="usuCod", nullable=false)
    public String getUsuCod() {
        return this.usuCod;
    }
    
    public void setUsuCod(String usuCod) {
        this.usuCod = usuCod;
    }

    
    @Column(name="EstCivCod")
    public int getEstCivCod() {
        return this.estCivCod;
    }
    
    public void setEstCivCod(int estCivCod) {
        this.estCivCod = estCivCod;
    }

    
    @Column(name="EstRegCod")
    public char getEstRegCod() {
        return this.estRegCod;
    }
    
    public void setEstRegCod(char estRegCod) {
        this.estRegCod = estRegCod;
    }

    
    @Column(name="TipUsuCod")
    public int getTipUsuCod() {
        return this.tipUsuCod;
    }
    
    public void setTipUsuCod(int tipUsuCod) {
        this.tipUsuCod = tipUsuCod;
    }

    
    @Column(name="UsuApeMat")
    public String getUsuApeMat() {
        return this.usuApeMat;
    }
    
    public void setUsuApeMat(String usuApeMat) {
        this.usuApeMat = usuApeMat;
    }

    
    @Column(name="UsuApePat")
    public String getUsuApePat() {
        return this.usuApePat;
    }
    
    public void setUsuApePat(String usuApePat) {
        this.usuApePat = usuApePat;
    }

    
    @Column(name="UsuFecNac")
    public Date getUsuFecNac() {
        return this.usuFecNac;
    }
    
    public void setUsuFecNac(Date usuFecNac) {
        this.usuFecNac = usuFecNac;
    }

    
    @Column(name="UsuHue")
    public byte[] getUsuHue() {
        return this.usuHue;
    }
    
    public void setUsuHue(byte[] usuHue) {
        this.usuHue = usuHue;
    }

    
    @Column(name="UsuLog")
    public String getUsuLog() {
        return this.usuLog;
    }
    
    public void setUsuLog(String usuLog) {
        this.usuLog = usuLog;
    }

    
    @Column(name="UsuNom")
    public String getUsuNom() {
        return this.usuNom;
    }
    
    public void setUsuNom(String usuNom) {
        this.usuNom = usuNom;
    }

    
    @Column(name="UsuPas")
    public String getUsuPas() {
        return this.usuPas;
    }
    
    public void setUsuPas(String usuPas) {
        this.usuPas = usuPas;
    }

    
    @Column(name="UsuSex")
    public char getUsuSex() {
        return this.usuSex;
    }
    
    public void setUsuSex(char usuSex) {
        this.usuSex = usuSex;
    }




}


